/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/monitoring/obligations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Monitoring Obligations */
        get: operations["listMonitoringObligations"];
        put?: never;
        /** Assign Monitoring Obligation */
        post: operations["assignMonitoringObligation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monitoring/breaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Monitoring Breach */
        post: operations["recordMonitoringBreach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/revalidation-triggers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Revalidation Triggers */
        get: operations["listRevalidationTriggers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MonitoringObligation: {
            id: string;
            modelId: string;
            ownerId: string;
            developerTeamId?: string;
            metric: string;
            /** Format: float */
            threshold: number;
            inBreach?: boolean;
            revalidationOnBreach?: boolean;
        };
        MonitoringObligationListData: {
            items: {
                id: string;
                modelId: string;
                ownerId: string;
                developerTeamId?: string;
                metric: string;
                /** Format: float */
                threshold: number;
                inBreach?: boolean;
                revalidationOnBreach?: boolean;
            }[];
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            timestamp?: string;
        };
        MonitoringObligationListResponse: {
            data: {
                items: {
                    id: string;
                    modelId: string;
                    ownerId: string;
                    developerTeamId?: string;
                    metric: string;
                    /** Format: float */
                    threshold: number;
                    inBreach?: boolean;
                    revalidationOnBreach?: boolean;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                timestamp?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        MonitoringObligationCreate: {
            modelId: string;
            ownerId: string;
            developerTeamId?: string;
            metric: string;
            /** Format: float */
            threshold: number;
            /** @default true */
            revalidationOnBreach: boolean;
        };
        MonitoringObligationResponse: {
            data: {
                id: string;
                modelId: string;
                ownerId: string;
                developerTeamId?: string;
                metric: string;
                /** Format: float */
                threshold: number;
                inBreach?: boolean;
                revalidationOnBreach?: boolean;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                timestamp?: string;
            };
        };
        MonitoringBreachCreate: {
            obligationId: string;
            /** Format: float */
            observedValue: number;
            /** Format: date-time */
            breachedAt: string;
        };
        MonitoringBreach: {
            id: string;
            obligationId: string;
            modelId?: string;
            /** Format: float */
            observedValue: number;
            /** Format: date-time */
            breachedAt: string;
            revalidationTriggered?: boolean;
        };
        MonitoringBreachResponse: {
            data: {
                id: string;
                obligationId: string;
                modelId?: string;
                /** Format: float */
                observedValue: number;
                /** Format: date-time */
                breachedAt: string;
                revalidationTriggered?: boolean;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                timestamp?: string;
            };
        };
        RevalidationTrigger: {
            id: string;
            modelId: string;
            /** @enum {string} */
            reason: "monitoring_breach" | "change_of_use" | "exception_expiry" | "scheduled" | "supervisory";
            /** @enum {string} */
            status: "open" | "queued" | "in_progress" | "completed";
            /** Format: date-time */
            triggeredAt?: string;
        };
        RevalidationTriggerListData: {
            items: {
                id: string;
                modelId: string;
                /** @enum {string} */
                reason: "monitoring_breach" | "change_of_use" | "exception_expiry" | "scheduled" | "supervisory";
                /** @enum {string} */
                status: "open" | "queued" | "in_progress" | "completed";
                /** Format: date-time */
                triggeredAt?: string;
            }[];
        };
        RevalidationTriggerListResponse: {
            data: {
                items: {
                    id: string;
                    modelId: string;
                    /** @enum {string} */
                    reason: "monitoring_breach" | "change_of_use" | "exception_expiry" | "scheduled" | "supervisory";
                    /** @enum {string} */
                    status: "open" | "queued" | "in_progress" | "completed";
                    /** Format: date-time */
                    triggeredAt?: string;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                timestamp?: string;
            };
        };
    };
    responses: {
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMonitoringObligations: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                modelId?: string;
                inBreach?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monitoring obligations page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                modelId: string;
                                ownerId: string;
                                developerTeamId?: string;
                                metric: string;
                                /** Format: float */
                                threshold: number;
                                inBreach?: boolean;
                                revalidationOnBreach?: boolean;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    assignMonitoringObligation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    modelId: string;
                    ownerId: string;
                    developerTeamId?: string;
                    metric: string;
                    /** Format: float */
                    threshold: number;
                    /** @default true */
                    revalidationOnBreach?: boolean;
                };
            };
        };
        responses: {
            /** @description Obligation assigned at approval */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            modelId: string;
                            ownerId: string;
                            developerTeamId?: string;
                            metric: string;
                            /** Format: float */
                            threshold: number;
                            inBreach?: boolean;
                            revalidationOnBreach?: boolean;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recordMonitoringBreach: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    obligationId: string;
                    /** Format: float */
                    observedValue: number;
                    /** Format: date-time */
                    breachedAt: string;
                };
            };
        };
        responses: {
            /** @description Breach recorded; revalidation may be triggered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            obligationId: string;
                            modelId?: string;
                            /** Format: float */
                            observedValue: number;
                            /** Format: date-time */
                            breachedAt: string;
                            revalidationTriggered?: boolean;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listRevalidationTriggers: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revalidation triggers page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                modelId: string;
                                /** @enum {string} */
                                reason: "monitoring_breach" | "change_of_use" | "exception_expiry" | "scheduled" | "supervisory";
                                /** @enum {string} */
                                status: "open" | "queued" | "in_progress" | "completed";
                                /** Format: date-time */
                                triggeredAt?: string;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
