/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { artefactRoutes } from "./artefact.routes.js";
export { determinationRoutes } from "./determination.routes.js";
export { vModelRoutes } from "./vmodel.routes.js";
