/**
 * DeclareConservatismOverlay handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { declareConservatismOverlay } from "@assayline/api-server/domains/conservatism/handlers";
import type { ConservatismDDDDependencies } from "@assayline/api-server/domains/conservatism";
import { createConservatismOverlay as createConservatismOverlayEntity } from "@assayline/factories/conservatism";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@assayline/tests/shared";
import { CONSERVATISM_USE_CASES } from "../__factories__/use-cases.js";

describe("DeclareConservatismOverlay", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConservatismDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConservatismDDDDependencies>(
      CONSERVATISM_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createConservatismOverlayEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeDeclareConservatismOverlay, "execute").mockResolvedValue(useCaseResult);

    await declareConservatismOverlay(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDeclareConservatismOverlay.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
