/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@assayline/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildConservatismDomainModule,
  buildFindingsDomainModule,
  buildIdentityDomainModule,
  buildInventoryDomainModule,
  buildMonitoringDomainModule,
  buildQuantificationDomainModule,
  buildSubmissionsDomainModule,
  buildSupervisoryDomainModule,
  buildTieringDomainModule,
  buildUseDomainModule,
  buildValidationDomainModule,
} from "../domains/index.js";
import type {
  ConservatismDomainModule,
  FindingsDomainModule,
  IdentityDomainModule,
  InventoryDomainModule,
  MonitoringDomainModule,
  QuantificationDomainModule,
  SubmissionsDomainModule,
  SupervisoryDomainModule,
  TieringDomainModule,
  UseDomainModule,
  ValidationDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private conservatismModule: ConservatismDomainModule | null = null;
  private findingsModule: FindingsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private inventoryModule: InventoryDomainModule | null = null;
  private monitoringModule: MonitoringDomainModule | null = null;
  private quantificationModule: QuantificationDomainModule | null = null;
  private submissionsModule: SubmissionsDomainModule | null = null;
  private supervisoryModule: SupervisoryDomainModule | null = null;
  private tieringModule: TieringDomainModule | null = null;
  private useModule: UseDomainModule | null = null;
  private validationModule: ValidationDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get conservatism domain module
   */
  getConservatismDependencies(): ConservatismDomainModule {
    if (!this.conservatismModule) {
      this.conservatismModule = buildConservatismDomainModule(this.dynamoClient);
    }
    return this.conservatismModule;
  }

  /**
   * Get findings domain module
   */
  getFindingsDependencies(): FindingsDomainModule {
    if (!this.findingsModule) {
      this.findingsModule = buildFindingsDomainModule(this.dynamoClient);
    }
    return this.findingsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get inventory domain module
   */
  getInventoryDependencies(): InventoryDomainModule {
    if (!this.inventoryModule) {
      this.inventoryModule = buildInventoryDomainModule(this.dynamoClient);
    }
    return this.inventoryModule;
  }

  /**
   * Get monitoring domain module
   */
  getMonitoringDependencies(): MonitoringDomainModule {
    if (!this.monitoringModule) {
      this.monitoringModule = buildMonitoringDomainModule(this.dynamoClient);
    }
    return this.monitoringModule;
  }

  /**
   * Get quantification domain module
   */
  getQuantificationDependencies(): QuantificationDomainModule {
    if (!this.quantificationModule) {
      this.quantificationModule = buildQuantificationDomainModule(this.dynamoClient);
    }
    return this.quantificationModule;
  }

  /**
   * Get submissions domain module
   */
  getSubmissionsDependencies(): SubmissionsDomainModule {
    if (!this.submissionsModule) {
      this.submissionsModule = buildSubmissionsDomainModule(this.dynamoClient);
    }
    return this.submissionsModule;
  }

  /**
   * Get supervisory domain module
   */
  getSupervisoryDependencies(): SupervisoryDomainModule {
    if (!this.supervisoryModule) {
      this.supervisoryModule = buildSupervisoryDomainModule(this.dynamoClient);
    }
    return this.supervisoryModule;
  }

  /**
   * Get tiering domain module
   */
  getTieringDependencies(): TieringDomainModule {
    if (!this.tieringModule) {
      this.tieringModule = buildTieringDomainModule(this.dynamoClient);
    }
    return this.tieringModule;
  }

  /**
   * Get use domain module
   */
  getUseDependencies(): UseDomainModule {
    if (!this.useModule) {
      this.useModule = buildUseDomainModule(this.dynamoClient);
    }
    return this.useModule;
  }

  /**
   * Get validation domain module
   */
  getValidationDependencies(): ValidationDomainModule {
    if (!this.validationModule) {
      this.validationModule = buildValidationDomainModule(this.dynamoClient);
    }
    return this.validationModule;
  }

  clearConservatismDependencies(): void { this.conservatismModule = null; }
  clearFindingsDependencies(): void { this.findingsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearInventoryDependencies(): void { this.inventoryModule = null; }
  clearMonitoringDependencies(): void { this.monitoringModule = null; }
  clearQuantificationDependencies(): void { this.quantificationModule = null; }
  clearSubmissionsDependencies(): void { this.submissionsModule = null; }
  clearSupervisoryDependencies(): void { this.supervisoryModule = null; }
  clearTieringDependencies(): void { this.tieringModule = null; }
  clearUseDependencies(): void { this.useModule = null; }
  clearValidationDependencies(): void { this.validationModule = null; }

  getConservatismDependenciesForRequest(): ConservatismDomainModule {
    return this.getConservatismDependencies();
  }

  getFindingsDependenciesForRequest(): FindingsDomainModule {
    return this.getFindingsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getInventoryDependenciesForRequest(): InventoryDomainModule {
    return this.getInventoryDependencies();
  }

  getMonitoringDependenciesForRequest(): MonitoringDomainModule {
    return this.getMonitoringDependencies();
  }

  getQuantificationDependenciesForRequest(): QuantificationDomainModule {
    return this.getQuantificationDependencies();
  }

  getSubmissionsDependenciesForRequest(): SubmissionsDomainModule {
    return this.getSubmissionsDependencies();
  }

  getSupervisoryDependenciesForRequest(): SupervisoryDomainModule {
    return this.getSupervisoryDependencies();
  }

  getTieringDependenciesForRequest(): TieringDomainModule {
    return this.getTieringDependencies();
  }

  getUseDependenciesForRequest(): UseDomainModule {
    return this.getUseDependencies();
  }

  getValidationDependenciesForRequest(): ValidationDomainModule {
    return this.getValidationDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.conservatismModule = null;
    this.findingsModule = null;
    this.identityModule = null;
    this.inventoryModule = null;
    this.monitoringModule = null;
    this.quantificationModule = null;
    this.submissionsModule = null;
    this.supervisoryModule = null;
    this.tieringModule = null;
    this.useModule = null;
    this.validationModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
