/**
 * Repository interface for LumpSumBuffer
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  LumpSumBufferEntity
} from "../models/lump-sum-buffer.entity.js";
import type {
  LumpSumBuffer
} from "../types/index.js";
/**
 * LumpSumBufferRepository Interface
 */
export interface LumpSumBufferRepository extends CreateReadRepository<LumpSumBufferEntity, LumpSumBuffer, string, Record<string, never>> {

}
