/**
 * ListUseException DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListUseExceptionsParams } from "@assayline/core/use";

export function createListUseExceptionRequest(overrides: Partial<ListUseExceptionsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
