/**
 * Handlers for Aggregate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConservatismDomainModule } from "../dependencies/conservatism-ddd.dependencies.js";
import type { GetConservatismAggregateInput } from "@assayline/services/conservatism";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/conservatism-overlays/aggregate
 * Operation: getConservatismAggregate
 */
export async function getConservatismAggregate(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ConservatismDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetConservatismAggregateInput = {};
  const result = await deps.useCases.aggregates.get.execute(input);
  return reply.code(200).send(result);
}


