/**
 * TierCriterium DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TierCriterium DTOs
 *
 * DDD: Application DTOs for TierCriterium use cases.
 */

import type { UpdateTierCriteriaRequestInput } from "@assayline/core/tiering/types";

export type GetTierCriteriaInput = {};

export type UpdateTierCriteriaInput = UpdateTierCriteriaRequestInput;

export type GetTierCriteriaOutput = {};

export type UpdateTierCriteriaOutput = {};
