/**
 * ExecuteGetRiskAppetiteStatement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetRiskAppetiteStatement Use Case
 *
 * DDD: Application use case for get RiskAppetite.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetRiskAppetiteStatementInput, GetRiskAppetiteStatementOutput } from "../dto/risk-appetite.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { RiskAppetiteRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetRiskAppetiteStatement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly riskAppetite: RiskAppetiteRepository
  ) {}

  async execute(input: GetRiskAppetiteStatementInput): Promise<GetRiskAppetiteStatementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.qntId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.riskAppetite.getRiskAppetiteStatement({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetRiskAppetiteStatementOutput;
  }
}
