/**
 * ExecuteRecordQuantification - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordQuantification Use Case
 *
 * DDD: Application use case for get Quantification.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordQuantificationInput, RecordQuantificationOutput } from "../dto/quantification.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { QuantificationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordQuantification {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly quantification: QuantificationRepository
  ) {}

  async execute(input: RecordQuantificationInput): Promise<RecordQuantificationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.qntId();

    // All field names extracted from OpenAPI spec: kpiSnapshot, modelId, quantifiedAmount, scope, status
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelId) {
      throw new ValidationError("modelId is required");
    }
    const modelId = (input as any).modelId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.quantification.recordQuantification({ modelId: modelId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${modelId}`);
    }

    return entity as RecordQuantificationOutput;
  }
}
