/**
 * ExecuteListLumpSumBuffers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLumpSumBuffers Use Case
 *
 * DDD: Application use case for list LumpSumBuffer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLumpSumBuffersInput, ListLumpSumBuffersOutput } from "../dto/lump-sum-buffer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { LumpSumBufferRepository } from "../ports";

export class ExecuteListLumpSumBuffers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly lumpSumBuffer: LumpSumBufferRepository
  ) {}

  async execute(input: ListLumpSumBuffersInput): Promise<ListLumpSumBuffersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.qntId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.lumpSumBuffer.listLumpSumBuffers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLumpSumBuffersOutput;
  }
}
