/**
 * ExecuteFixLumpSumBuffer - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteFixLumpSumBuffer Use Case
 *
 * DDD: Application use case for get LumpSumBuffer.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { FixLumpSumBufferInput, FixLumpSumBufferOutput } from "../dto/lump-sum-buffer.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { LumpSumBufferRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteFixLumpSumBuffer {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly lumpSumBuffer: LumpSumBufferRepository
  ) {}

  async execute(input: FixLumpSumBufferInput): Promise<FixLumpSumBufferOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.qntId();

    // All field names extracted from OpenAPI spec: amount, modelId, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelId) {
      throw new ValidationError("modelId is required");
    }
    const modelId = (input as any).modelId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.lumpSumBuffer.fixLumpSumBuffer({ modelId: modelId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${modelId}`);
    }

    return entity as FixLumpSumBufferOutput;
  }
}
