/**
 * TaskRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TaskRepository Port
 *
 * DDD: Application port for taskrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListValidationTasksInput, ListValidationTasksOutput, PlaceValidationTaskInput, PlaceValidationTaskOutput } from "../dto/task.dto";
export interface TaskRepository {
  listValidationTasks(input: ListValidationTasksInput): Promise<ListValidationTasksOutput>;
  placeValidationTask(input: PlaceValidationTaskInput): Promise<PlaceValidationTaskOutput>;
}

export type { ListValidationTasksInput, ListValidationTasksOutput, PlaceValidationTaskInput, PlaceValidationTaskOutput } from "../dto/task.dto";
