/**
 * RemediationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RemediationRepository Port
 *
 * DDD: Application port for remediationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { UpdateRemediationPlanInput, UpdateRemediationPlanOutput } from "../dto/remediation.dto";
export interface RemediationRepository {
  updateRemediationPlan(input: UpdateRemediationPlanInput): Promise<UpdateRemediationPlanOutput>;
}

export type { UpdateRemediationPlanInput, UpdateRemediationPlanOutput } from "../dto/remediation.dto";
