/**
 * SupervisoryPackRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SupervisoryPackRepository Port
 *
 * DDD: Application port for supervisorypackrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AssembleSupervisoryPackInput, AssembleSupervisoryPackOutput, GetSupervisoryPackInput, GetSupervisoryPackOutput } from "../dto/supervisory-pack.dto";
export interface SupervisoryPackRepository {
  assembleSupervisoryPack(input: AssembleSupervisoryPackInput): Promise<AssembleSupervisoryPackOutput>;
  getSupervisoryPack(input: GetSupervisoryPackInput): Promise<GetSupervisoryPackOutput>;
}

export type { AssembleSupervisoryPackInput, AssembleSupervisoryPackOutput, GetSupervisoryPackInput, GetSupervisoryPackOutput } from "../dto/supervisory-pack.dto";
