/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Quantification Domain Use Cases
 * 
 * List of all use case names for the quantification domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const QUANTIFICATION_USE_CASES = [
  "executeFixLumpSumBuffer",
  "executeGetRiskAppetiteStatement",
  "executeListLumpSumBuffers",
  "executeListQuantifications",
  "executeRecordQuantification",
  "executeUpdateRiskAppetiteStatement"
] as const;
