/**
 * LumpSumBuffer DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LumpSumBuffer DTOs
 *
 * DDD: Application DTOs for LumpSumBuffer use cases.
 */

import type { FixLumpSumBufferRequestInput } from "@assayline/core/quantification/types";

export type ListLumpSumBuffersInput = {};

export type FixLumpSumBufferInput = FixLumpSumBufferRequestInput;

export type ListLumpSumBuffersOutput = {};

export type FixLumpSumBufferOutput = {};
