/**
 * Quantification DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Quantification DTOs
 *
 * DDD: Application DTOs for Quantification use cases.
 */

import type { ListQuantificationsParams, RecordQuantificationRequestInput } from "@assayline/core/quantification/types";

export type ListQuantificationsInput = ListQuantificationsParams;

export type RecordQuantificationInput = RecordQuantificationRequestInput;

export type ListQuantificationsOutput = {};

export type RecordQuantificationOutput = {};
