/**
 * RiskAppetite DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskAppetite DTOs
 *
 * DDD: Application DTOs for RiskAppetite use cases.
 */

import type { UpdateRiskAppetiteStatementRequestInput } from "@assayline/core/quantification/types";

export type GetRiskAppetiteStatementInput = {};

export type UpdateRiskAppetiteStatementInput = UpdateRiskAppetiteStatementRequestInput;

export type GetRiskAppetiteStatementOutput = {};

export type UpdateRiskAppetiteStatementOutput = {};
