/**
 * Submissions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Submissions Domain Module - Composition root
 *
 * DDD: Composition root for submissions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CompletenessCheckRepositoryAdapter,
  ReturnRepositoryAdapter,
  SubmissionRepositoryAdapter,
} from "@assayline/adapters/submissions";
import { getIdGeneratorService } from "@assayline/adapters";
import type { AdapterDynamoDBClient } from "@assayline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCheckSubmissionCompleteness,
  ExecuteCreateSubmission,
  ExecuteListSubmissions,
  ExecuteReturnSubmission,
} from "@assayline/services/submissions/usecases";
// Ports (interfaces)
import type {
  CompletenessCheckRepository,
  ReturnRepository,
  SubmissionRepository,
} from "@assayline/services/submissions/ports";

export interface SubmissionsDomainModule {
  repos: {
    completenessChecks: CompletenessCheckRepository;
    returns: ReturnRepository;
    submissions: SubmissionRepository;
  };
  useCases: {
    completenessChecks: {
      get: ExecuteCheckSubmissionCompleteness;
    };
    returns: {
      get: ExecuteReturnSubmission;
    };
    submissions: {
      create: ExecuteCreateSubmission;
      list: ExecuteListSubmissions;
    };
  };
}

export function buildSubmissionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SubmissionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      completenessChecks?: CompletenessCheckRepository;
      returns?: ReturnRepository;
      submissions?: SubmissionRepository;
    } = {};

    obj.completenessChecks = new CompletenessCheckRepositoryAdapter(dynamoClient);
    obj.returns = new ReturnRepositoryAdapter(dynamoClient);
    obj.submissions = new SubmissionRepositoryAdapter(dynamoClient);
    return {
      completenessChecks: obj.completenessChecks!,
      returns: obj.returns!,
      submissions: obj.submissions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    completenessChecks: {
      get: new ExecuteCheckSubmissionCompleteness(executionContext, idGenerator, repos.completenessChecks),
    },
    returns: {
      get: new ExecuteReturnSubmission(executionContext, idGenerator, repos.returns),
    },
    submissions: {
      create: new ExecuteCreateSubmission(executionContext, idGenerator, repos.submissions),
      list: new ExecuteListSubmissions(executionContext, idGenerator, repos.submissions),
    },
  };
  return { repos, useCases: useCases as SubmissionsDomainModule["useCases"] };
}
