/**
 * Authorise DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Authorise DTOs
 *
 * DDD: Application DTOs for Authorise use cases.
 */

import type { AuthoriseUseExceptionParams, AuthoriseUseExceptionRequestInput } from "@assayline/core/use/types";

export type AuthoriseUseExceptionInput = AuthoriseUseExceptionParams & AuthoriseUseExceptionRequestInput;

export type AuthoriseUseExceptionOutput = {};
