/**
 * Supervisory DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Supervisory Domain Module - Composition root
 *
 * DDD: Composition root for supervisory domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  RemediationRepositoryAdapter,
  SupervisoryAddOnRepositoryAdapter,
  SupervisoryPackRepositoryAdapter,
} from "@assayline/adapters/supervisory";
import { getIdGeneratorService } from "@assayline/adapters";
import type { AdapterDynamoDBClient } from "@assayline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAssembleSupervisoryPack,
  ExecuteGetSupervisoryPack,
  ExecuteListSupervisoryAddOns,
  ExecuteRecordSupervisoryAddOn,
  ExecuteUpdateRemediationPlan,
} from "@assayline/services/supervisory/usecases";
// Ports (interfaces)
import type {
  RemediationRepository,
  SupervisoryAddOnRepository,
  SupervisoryPackRepository,
} from "@assayline/services/supervisory/ports";

export interface SupervisoryDomainModule {
  repos: {
    addOns: SupervisoryAddOnRepository;
    packs: SupervisoryPackRepository;
    remediations: RemediationRepository;
  };
  useCases: {
    addOns: {
      get: ExecuteRecordSupervisoryAddOn;
      list: ExecuteListSupervisoryAddOns;
    };
    packs: {
      get: ExecuteGetSupervisoryPack;
    };
    remediations: {
      update: ExecuteUpdateRemediationPlan;
    };
  };
}

export function buildSupervisoryDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SupervisoryDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      addOns?: SupervisoryAddOnRepository;
      packs?: SupervisoryPackRepository;
      remediations?: RemediationRepository;
    } = {};

    obj.addOns = new SupervisoryAddOnRepositoryAdapter(dynamoClient);
    obj.packs = new SupervisoryPackRepositoryAdapter(dynamoClient);
    obj.remediations = new RemediationRepositoryAdapter(dynamoClient);
    return {
      addOns: obj.addOns!,
      packs: obj.packs!,
      remediations: obj.remediations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    addOns: {
      get: new ExecuteRecordSupervisoryAddOn(executionContext, idGenerator, repos.addOns),
      list: new ExecuteListSupervisoryAddOns(executionContext, idGenerator, repos.addOns),
    },
    packs: {
      get: new ExecuteGetSupervisoryPack(executionContext, idGenerator, repos.packs),
    },
    remediations: {
      update: new ExecuteUpdateRemediationPlan(executionContext, idGenerator, repos.remediations),
    },
  };
  return { repos, useCases: useCases as SupervisoryDomainModule["useCases"] };
}
