/**
 * LumpSumBuffer Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { LumpSumBufferEntity } from "@assayline/core/quantification/models/index.js";
import { quantificationSchemas } from "@assayline/core/quantification";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "qnt";

export function createLumpSumBuffer(overrides: Partial<LumpSumBufferEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    amount: overrides.amount ?? {
      amount: "",
      currency: ""
    },
    rationale: overrides.rationale ?? faker.lorem.word(),
    ...overrides,
  };

  return quantificationSchemas.LumpSumBuffer.parse(raw);
}

export function lumpSumBufferBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createLumpSumBuffer(overrides));
}
