/**
 * AuthoriseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuthoriseRepository Port
 *
 * DDD: Application port for authoriserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AuthoriseUseExceptionInput, AuthoriseUseExceptionOutput } from "../dto/authorise.dto";
export interface AuthoriseRepository {
  authoriseUseException(input: AuthoriseUseExceptionInput): Promise<AuthoriseUseExceptionOutput>;
}

export type { AuthoriseUseExceptionInput, AuthoriseUseExceptionOutput } from "../dto/authorise.dto";
