/**
 * PermittedUseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PermittedUseRepository Port
 *
 * DDD: Application port for permitteduserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetPermittedUseInput, GetPermittedUseOutput, SetPermittedUseInput, SetPermittedUseOutput } from "../dto/permitted-use.dto";
export interface PermittedUseRepository {
  getPermittedUse(input: GetPermittedUseInput): Promise<GetPermittedUseOutput>;
  setPermittedUse(input: SetPermittedUseInput): Promise<SetPermittedUseOutput>;
}

export type { GetPermittedUseInput, GetPermittedUseOutput, SetPermittedUseInput, SetPermittedUseOutput } from "../dto/permitted-use.dto";
