/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Use Domain Use Cases
 * 
 * List of all use case names for the use domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const USE_USE_CASES = [
  "executeAuthoriseUseException",
  "executeGetPermittedUse",
  "executeListUseExceptions",
  "executeRequestUseException",
  "executeSetPermittedUse"
] as const;
