/**
 * ListArtefact DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListArtefactsParams } from "@assayline/core/inventory";

export function createListArtefactRequest(overrides: Partial<ListArtefactsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
