/**
 * Handlers for Quantification
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { QuantificationDomainModule } from "../dependencies/quantification-ddd.dependencies.js";
import type { ListQuantificationsInput, RecordQuantificationInput } from "@assayline/services/quantification";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/quantifications
 * Operation: listQuantifications
 */
export async function listQuantifications(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], modelId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: QuantificationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListQuantificationsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.quantifications.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/quantifications
 * Operation: recordQuantification
 */
export async function recordQuantification(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: QuantificationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordQuantificationInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.quantifications.get.execute(input);
  return reply.code(201).send(result);
}


