/**
 * RemediationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RemediationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RemediationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RemediationRepository,
} from "@assayline/services/supervisory";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RemediationRepositoryDdb } from "./remediation-repository.ddb.js";

/**
 * RemediationRepositoryAdapter
 *
 * Implements RemediationRepository port for infrastructure layer.
 */
export class RemediationRepositoryAdapter implements RemediationRepository {
  private readonly ddb: RemediationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RemediationRepositoryDdb(this.dynamoClient);
  }

  async updateRemediationPlan(input: Parameters<RemediationRepository['updateRemediationPlan']>[0]): Promise<Awaited<ReturnType<RemediationRepository['updateRemediationPlan']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateRemediationPlan(input);
  }
}
