/**
 * SupervisoryPackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SupervisoryPackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SupervisoryPackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SupervisoryPackRepository,
} from "@assayline/services/supervisory";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SupervisoryPackRepositoryDdb } from "./supervisory-pack-repository.ddb.js";

/**
 * SupervisoryPackRepositoryAdapter
 *
 * Implements SupervisoryPackRepository port for infrastructure layer.
 */
export class SupervisoryPackRepositoryAdapter implements SupervisoryPackRepository {
  private readonly ddb: SupervisoryPackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SupervisoryPackRepositoryDdb(this.dynamoClient);
  }

  async assembleSupervisoryPack(input: Parameters<SupervisoryPackRepository['assembleSupervisoryPack']>[0]): Promise<Awaited<ReturnType<SupervisoryPackRepository['assembleSupervisoryPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.assembleSupervisoryPack(input);
  }

  async getSupervisoryPack(input: Parameters<SupervisoryPackRepository['getSupervisoryPack']>[0]): Promise<Awaited<ReturnType<SupervisoryPackRepository['getSupervisoryPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSupervisoryPack(input);
  }
}
