/**
 * GetTierCriteria handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getTierCriteria } from "@assayline/api-server/domains/tiering/handlers";
import type { TieringDDDDependencies } from "@assayline/api-server/domains/tiering";
import { createTierCriterium as createTierCriteriumEntity } from "@assayline/factories/tiering";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@assayline/tests/shared";
import { TIERING_USE_CASES } from "../__factories__/use-cases.js";

describe("GetTierCriteria", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TieringDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TieringDDDDependencies>(
      TIERING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = createTierCriteriumEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetTierCriteria, "execute").mockResolvedValue(useCaseResult);

    await getTierCriteria(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetTierCriteria.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
