/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@assayline/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "conservatism", "findings", "identity", "inventory", "monitoring", "quantification", "submissions", "supervisory", "tiering", "use", "validation"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      conservatism: [{ method: "GET", path: "/v1/conservatism-overlays" }, { method: "POST", path: "/v1/conservatism-overlays" }, { method: "GET", path: "/v1/conservatism-overlays/aggregate" }],
      findings: [{ method: "GET", path: "/v1/findings" }, { method: "POST", path: "/v1/findings" }, { method: "POST", path: "/v1/findings/:findingId/close" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      inventory: [{ method: "GET", path: "/v1/artefacts" }, { method: "POST", path: "/v1/artefacts" }, { method: "POST", path: "/v1/artefacts/:artefactId/determination" }, { method: "GET", path: "/v1/models" }, { method: "GET", path: "/v1/models/:modelId" }],
      monitoring: [{ method: "GET", path: "/v1/monitoring/obligations" }, { method: "POST", path: "/v1/monitoring/obligations" }, { method: "POST", path: "/v1/monitoring/breaches" }, { method: "GET", path: "/v1/revalidation-triggers" }],
      quantification: [{ method: "GET", path: "/v1/quantifications" }, { method: "POST", path: "/v1/quantifications" }, { method: "GET", path: "/v1/risk-appetite" }, { method: "PUT", path: "/v1/risk-appetite" }, { method: "GET", path: "/v1/lump-sum-buffers" }, { method: "POST", path: "/v1/lump-sum-buffers" }],
      submissions: [{ method: "GET", path: "/v1/submissions" }, { method: "POST", path: "/v1/submissions" }, { method: "POST", path: "/v1/submissions/:submissionId/completeness-check" }, { method: "POST", path: "/v1/submissions/:submissionId/return" }],
      supervisory: [{ method: "GET", path: "/v1/supervisory-add-ons" }, { method: "POST", path: "/v1/supervisory-add-ons" }, { method: "PUT", path: "/v1/supervisory-add-ons/:addOnId/remediation" }, { method: "POST", path: "/v1/supervisory-packs" }, { method: "GET", path: "/v1/supervisory-packs/:packId" }],
      tiering: [{ method: "GET", path: "/v1/models/:modelId/tier-assessments" }, { method: "POST", path: "/v1/models/:modelId/tier-assessments" }, { method: "GET", path: "/v1/tier-criteria" }, { method: "PUT", path: "/v1/tier-criteria" }],
      use: [{ method: "GET", path: "/v1/models/:modelId/permitted-use" }, { method: "PUT", path: "/v1/models/:modelId/permitted-use" }, { method: "GET", path: "/v1/use-exceptions" }, { method: "POST", path: "/v1/use-exceptions" }, { method: "POST", path: "/v1/use-exceptions/:exceptionId/authorise" }],
      validation: [{ method: "GET", path: "/v1/validation/slots" }, { method: "POST", path: "/v1/validation/slots" }, { method: "GET", path: "/v1/validation/engagements" }, { method: "POST", path: "/v1/validation/engagements" }, { method: "GET", path: "/v1/validation/engagements/:engagementId/tasks" }, { method: "POST", path: "/v1/validation/engagements/:engagementId/tasks" }, { method: "GET", path: "/v1/validation/capacity-forecast" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
