/**
 * ListRevalidationTrigger DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListRevalidationTriggersParams } from "@assayline/core/monitoring";

export function createListRevalidationTriggerRequest(overrides: Partial<ListRevalidationTriggersParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
