/**
 * Repository interface for CapacityForecast
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CapacityForecastEntity
} from "../models/capacity-forecast.entity.js";
import type {
  GetCapacityForecastParams
} from "../types/index.js";
/**
 * CapacityForecastRepository Interface
 */
export interface CapacityForecastRepository extends ReadRepository<CapacityForecastEntity, string, GetCapacityForecastParams> {

}
