/**
 * VModel DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModel DTOs
 *
 * DDD: Application DTOs for VModel use cases.
 */

import type { GetModelParams, ListModelsParams } from "@assayline/core/inventory/types";

export type ListModelsInput = ListModelsParams;

export type GetModelInput = GetModelParams;

export type ListModelsOutput = {};

export type GetModelOutput = {};
