/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { breachRoutes } from "./breach.routes.js";
export { obligationRoutes } from "./obligation.routes.js";
export { revalidationTriggerRoutes } from "./revalidation-trigger.routes.js";
