/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Inventory Domain Use Cases
 * 
 * List of all use case names for the inventory domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const INVENTORY_USE_CASES = [
  "executeDetermineArtefact",
  "executeGetModel",
  "executeListArtefacts",
  "executeListModels",
  "executeRegisterArtefact"
] as const;
