/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @assayline/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@assayline/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@assayline/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@assayline/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@assayline/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@assayline/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _conservatism from "./conservatism/index.js";
import * as _findings from "./findings/index.js";
import * as _identity from "./identity/index.js";
import * as _inventory from "./inventory/index.js";
import * as _monitoring from "./monitoring/index.js";
import * as _quantification from "./quantification/index.js";
import * as _submissions from "./submissions/index.js";
import * as _supervisory from "./supervisory/index.js";
import * as _tiering from "./tiering/index.js";
import * as _use from "./use/index.js";
import * as _validation from "./validation/index.js";

// Export as namespaces
export const _shared = __shared;
export const conservatism = _conservatism;
export const findings = _findings;
export const identity = _identity;
export const inventory = _inventory;
export const monitoring = _monitoring;
export const quantification = _quantification;
export const submissions = _submissions;
export const supervisory = _supervisory;
export const tiering = _tiering;
export const use = _use;
export const validation = _validation;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@assayline/core"; activity.types.*
//   - Direct exports: import * from "@assayline/core/activity/types/index.js"
//   - Direct exports: import * from "@assayline/core/activity/repositories/index.js"
//   - Direct exports: import * from "@assayline/core/activity/models/index.js"
//   - Direct exports: import * from "@assayline/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Conservatism Service
export { schemas as ConservatismSchemas } from "./conservatism/schemas/conservatism.schemas.js";

// Findings Service
export { schemas as FindingsSchemas } from "./findings/schemas/findings.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Inventory Service
export { schemas as InventorySchemas } from "./inventory/schemas/inventory.schemas.js";

// Monitoring Service
export { schemas as MonitoringSchemas } from "./monitoring/schemas/monitoring.schemas.js";

// Quantification Service
export { schemas as QuantificationSchemas } from "./quantification/schemas/quantification.schemas.js";

// Submissions Service
export { schemas as SubmissionsSchemas } from "./submissions/schemas/submissions.schemas.js";

// Supervisory Service
export { schemas as SupervisorySchemas } from "./supervisory/schemas/supervisory.schemas.js";

// Tiering Service
export { schemas as TieringSchemas } from "./tiering/schemas/tiering.schemas.js";

// Use Service
export { schemas as UseSchemas } from "./use/schemas/use.schemas.js";

// Validation Service
export { schemas as ValidationSchemas } from "./validation/schemas/validation.schemas.js";

