/**
 * Repository interface for Artefact
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ArtefactEntity
} from "../models/artefact.entity.js";
import type {
  ListArtefactsParams,
  Artefact
} from "../types/index.js";
/**
 * ArtefactRepository Interface
 */
export interface ArtefactRepository extends CreateReadRepository<ArtefactEntity, Artefact, string, ListArtefactsParams> {

}
