/**
 * ExecuteUpdateRemediationPlan - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateRemediationPlan Use Case
 *
 * DDD: Application use case for update Remediation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateRemediationPlanInput, UpdateRemediationPlanOutput } from "../dto/remediation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { RemediationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateRemediationPlan {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly remediation: RemediationRepository
  ) {}

  async execute(input: UpdateRemediationPlanInput): Promise<UpdateRemediationPlanOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.spvId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).addOnId) {
      throw new ValidationError("addOnId is required");
    }
    const addonId = (input as any).addOnId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.remediation.updateRemediationPlan({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateRemediationPlanOutput;
  }
}
