/**
 * ExecuteAssembleSupervisoryPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAssembleSupervisoryPack Use Case
 *
 * DDD: Application use case for get SupervisoryPack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AssembleSupervisoryPackInput, AssembleSupervisoryPackOutput } from "../dto/supervisory-pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { SupervisoryPackRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteAssembleSupervisoryPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly supervisoryPack: SupervisoryPackRepository
  ) {}

  async execute(input: AssembleSupervisoryPackInput): Promise<AssembleSupervisoryPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.spvId();

    // All field names extracted from OpenAPI spec: asOf, examinationReference, scope
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.supervisoryPack.assembleSupervisoryPack({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as AssembleSupervisoryPackOutput;
  }
}
