/**
 * ConservatismOverlay Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ConservatismOverlayEntity } from "@assayline/core/conservatism/models/index.js";
import { conservatismSchemas } from "@assayline/core/conservatism";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cns";

export function createConservatismOverlay(overrides: Partial<ConservatismOverlayEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    location: overrides.location ?? faker.lorem.word(),
    magnitude: overrides.magnitude ?? {
      amount: "",
      currency: ""
    },
    modelId: overrides.modelId ?? faker.string.uuid(),
    status: overrides.status ?? "declared",
    ...overrides,
  };

  return conservatismSchemas.ConservatismOverlay.parse(raw);
}

export function conservatismOverlayBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createConservatismOverlay(overrides));
}
