/**
 * Findings DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Findings Domain Module - Composition root
 *
 * DDD: Composition root for findings domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CloseRepositoryAdapter,
  FindingRepositoryAdapter,
} from "@assayline/adapters/findings";
import { getIdGeneratorService } from "@assayline/adapters";
import type { AdapterDynamoDBClient } from "@assayline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCloseFinding,
  ExecuteListFindings,
  ExecuteRaiseFinding,
} from "@assayline/services/findings/usecases";
// Ports (interfaces)
import type {
  CloseRepository,
  FindingRepository,
} from "@assayline/services/findings/ports";

export interface FindingsDomainModule {
  repos: {
    closes: CloseRepository;
    findings: FindingRepository;
  };
  useCases: {
    closes: {
      get: ExecuteCloseFinding;
    };
    findings: {
      get: ExecuteRaiseFinding;
      list: ExecuteListFindings;
    };
  };
}

export function buildFindingsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): FindingsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      closes?: CloseRepository;
      findings?: FindingRepository;
    } = {};

    obj.closes = new CloseRepositoryAdapter(dynamoClient);
    obj.findings = new FindingRepositoryAdapter(dynamoClient);
    return {
      closes: obj.closes!,
      findings: obj.findings!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    closes: {
      get: new ExecuteCloseFinding(executionContext, idGenerator, repos.closes),
    },
    findings: {
      get: new ExecuteRaiseFinding(executionContext, idGenerator, repos.findings),
      list: new ExecuteListFindings(executionContext, idGenerator, repos.findings),
    },
  };
  return { repos, useCases: useCases as FindingsDomainModule["useCases"] };
}
