/**
 * ConservatismOverlay Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/conservatism.openapi.types.js";
import { schemas } from "../schemas/conservatism.schemas.js";

/**
 * Entity: ConservatismOverlayEntity
 * Description: Represents the ConservatismOverlay domain model.
 * Source: schemas.ConservatismOverlay
 * Type: Domain Entity (API)
 */
export const ConservatismOverlayEntitySchema = schemas.ConservatismOverlay;
export type ConservatismOverlayEntity = components["schemas"]["ConservatismOverlay"];
