/**
 * Handlers for Engagement
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ValidationDomainModule } from "../dependencies/validation-ddd.dependencies.js";
import type { CreateValidationEngagementInput, ListValidationEngagementsInput } from "@assayline/services/validation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/validation/engagements
 * Operation: listValidationEngagements
 */
export async function listValidationEngagements(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], modelId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ValidationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListValidationEngagementsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.engagements.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/validation/engagements
 * Operation: createValidationEngagement
 */
export async function createValidationEngagement(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ValidationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateValidationEngagementInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.engagements.create.execute(input);
  return reply.code(201).send(result);
}


