/**
 * Handlers for Slot
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ValidationDomainModule } from "../dependencies/validation-ddd.dependencies.js";
import type { AllocateValidationSlotInput, ListValidationSlotsInput } from "@assayline/services/validation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/validation/slots
 * Operation: listValidationSlots
 */
export async function listValidationSlots(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ValidationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListValidationSlotsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.slots.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/validation/slots
 * Operation: allocateValidationSlot
 */
export async function allocateValidationSlot(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ValidationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AllocateValidationSlotInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.slots.get.execute(input);
  return reply.code(201).send(result);
}


