/**
 * Engagement DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Engagement DTOs
 *
 * DDD: Application DTOs for Engagement use cases.
 */

import type { CreateValidationEngagementRequestInput, ListValidationEngagementsParams } from "@assayline/core/validation/types";

export type ListValidationEngagementsInput = ListValidationEngagementsParams;

export type CreateValidationEngagementInput = CreateValidationEngagementRequestInput;

export type ListValidationEngagementsOutput = {};

export type CreateValidationEngagementOutput = {};
