/**
 * Task DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Task DTOs
 *
 * DDD: Application DTOs for Task use cases.
 */

import type { ListValidationTasksParams, PlaceValidationTaskParams, PlaceValidationTaskRequestInput } from "@assayline/core/validation/types";

export type ListValidationTasksInput = ListValidationTasksParams;

export type PlaceValidationTaskInput = PlaceValidationTaskParams & PlaceValidationTaskRequestInput;

export type ListValidationTasksOutput = {};

export type PlaceValidationTaskOutput = {};
