/**
 * Repository interface for TierCriterium
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TierCriteriumEntity
} from "../models/tier-criterium.entity.js";
import type {
  UpdateTierCriteriaRequestInput
} from "../types/index.js";
/**
 * TierCriteriumRepository Interface
 */
export interface TierCriteriumRepository extends UpdateReadRepository<TierCriteriumEntity, UpdateTierCriteriaRequestInput, string, Record<string, never>> {

}
