/**
 * GetSupervisoryPack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSupervisoryPack } from "@assayline/api-server/domains/supervisory/handlers";
import type { SupervisoryDDDDependencies } from "@assayline/api-server/domains/supervisory";
import { createSupervisoryPack as createSupervisoryPackEntity } from "@assayline/factories/supervisory";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@assayline/tests/shared";
import { SUPERVISORY_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSupervisoryPack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SupervisoryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SupervisoryDDDDependencies>(
      SUPERVISORY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createSupervisoryPackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSupervisoryPack, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { packId: entity.id };

    await getSupervisoryPack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSupervisoryPack.execute).toHaveBeenCalledWith(expect.objectContaining({ packId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { packId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetSupervisoryPack, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getSupervisoryPack(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
