/**
 * ListSupervisoryAddOns handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listSupervisoryAddOns } from "@assayline/api-server/domains/supervisory/handlers";
import type { SupervisoryDDDDependencies } from "@assayline/api-server/domains/supervisory";
import { createSupervisoryAddOn as createSupervisoryAddOnEntity } from "@assayline/factories/supervisory";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@assayline/tests/shared";
import { SUPERVISORY_USE_CASES } from "../__factories__/use-cases.js";

describe("ListSupervisoryAddOns", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SupervisoryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SupervisoryDDDDependencies>(
      SUPERVISORY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createSupervisoryAddOnEntity({ orgId }),
      createSupervisoryAddOnEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListSupervisoryAddOns, "execute").mockResolvedValue(useCaseResult);

    await listSupervisoryAddOns(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListSupervisoryAddOns.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
