/**
 * RecordSupervisoryAddOn handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { recordSupervisoryAddOn } from "@assayline/api-server/domains/supervisory/handlers";
import type { SupervisoryDDDDependencies } from "@assayline/api-server/domains/supervisory";
import { createSupervisoryAddOn as createSupervisoryAddOnEntity } from "@assayline/factories/supervisory";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@assayline/tests/shared";
import { SUPERVISORY_USE_CASES } from "../__factories__/use-cases.js";

describe("RecordSupervisoryAddOn", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SupervisoryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SupervisoryDDDDependencies>(
      SUPERVISORY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createSupervisoryAddOnEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRecordSupervisoryAddOn, "execute").mockResolvedValue(useCaseResult);

    await recordSupervisoryAddOn(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRecordSupervisoryAddOn.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
