/**
 * Routes for TierAssessment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { assessModelTier, listTierAssessments } from "../handlers/tier-assessment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function tierAssessmentRoutes(fastify: FastifyInstance) {
  // POST /v1/models/{modelId}/tier-assessments (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/models/:modelId/tier-assessments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { modelId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTieringDependenciesForRequest();
        await assessModelTier(request, reply, deps);
      });
    }
  );


  // GET /v1/models/{modelId}/tier-assessments (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/models/:modelId/tier-assessments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { modelId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTieringDependenciesForRequest();
        await listTierAssessments(request, reply, deps);
      });
    }
  );


}
