/**
 * Handlers for PermittedUse
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { UseDomainModule } from "../dependencies/use-ddd.dependencies.js";
import type { GetPermittedUseInput, SetPermittedUseInput } from "@assayline/services/use";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/models/{modelId}/permitted-use
 * Operation: getPermittedUse
 */
export async function getPermittedUse(
  request: FastifyRequest<{ Params: { modelId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: UseDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPermittedUseInput = {
    modelId: request.params.modelId,
  };
  const result = await deps.useCases.permittedUses.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/models/{modelId}/permitted-use
 * Operation: setPermittedUse
 */
export async function setPermittedUse(
  request: FastifyRequest<{ Params: { modelId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: UseDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SetPermittedUseInput = {
    modelId: request.params.modelId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.permittedUses.update.execute(input);
  return reply.code(200).send(result);
}


