/**
 * CreateSubmission handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createSubmission } from "@assayline/api-server/domains/submissions/handlers";
import type { SubmissionsDDDDependencies } from "@assayline/api-server/domains/submissions";
import { createSubmission as createSubmissionEntity } from "@assayline/factories/submissions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@assayline/tests/shared";
import { SUBMISSIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateSubmission", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SubmissionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SubmissionsDDDDependencies>(
      SUBMISSIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createSubmissionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateSubmission, "execute").mockResolvedValue(useCaseResult);

    await createSubmission(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateSubmission.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
