/**
 * ListSubmissions handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listSubmissions } from "@assayline/api-server/domains/submissions/handlers";
import type { SubmissionsDDDDependencies } from "@assayline/api-server/domains/submissions";
import { createSubmission as createSubmissionEntity } from "@assayline/factories/submissions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@assayline/tests/shared";
import { SUBMISSIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListSubmissions", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SubmissionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SubmissionsDDDDependencies>(
      SUBMISSIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createSubmissionEntity({ orgId }),
      createSubmissionEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListSubmissions, "execute").mockResolvedValue(useCaseResult);

    await listSubmissions(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListSubmissions.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
