/**
 * QuantificationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QuantificationRepository Port
 *
 * DDD: Application port for quantificationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListQuantificationsInput, ListQuantificationsOutput, RecordQuantificationInput, RecordQuantificationOutput } from "../dto/quantification.dto";
export interface QuantificationRepository {
  listQuantifications(input: ListQuantificationsInput): Promise<ListQuantificationsOutput>;
  recordQuantification(input: RecordQuantificationInput): Promise<RecordQuantificationOutput>;
}

export type { ListQuantificationsInput, ListQuantificationsOutput, RecordQuantificationInput, RecordQuantificationOutput } from "../dto/quantification.dto";
