/**
 * RiskAppetiteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskAppetiteRepository Port
 *
 * DDD: Application port for riskappetiterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetRiskAppetiteStatementInput, GetRiskAppetiteStatementOutput, UpdateRiskAppetiteStatementInput, UpdateRiskAppetiteStatementOutput } from "../dto/risk-appetite.dto";
export interface RiskAppetiteRepository {
  getRiskAppetiteStatement(input: GetRiskAppetiteStatementInput): Promise<GetRiskAppetiteStatementOutput>;
  updateRiskAppetiteStatement(input: UpdateRiskAppetiteStatementInput): Promise<UpdateRiskAppetiteStatementOutput>;
}

export type { GetRiskAppetiteStatementInput, GetRiskAppetiteStatementOutput, UpdateRiskAppetiteStatementInput, UpdateRiskAppetiteStatementOutput } from "../dto/risk-appetite.dto";
