/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the use domain.
 * Use these factories in tests to create test data.
 */

export { createPermittedUse } from "./permitted-use/entity/permitted-use.entity.factory.js";
export { createUseException } from "./use-exception/entity/use-exception.entity.factory.js";
