/**
 * SupervisoryAddOn DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SupervisoryAddOn DTOs
 *
 * DDD: Application DTOs for SupervisoryAddOn use cases.
 */

import type { ListSupervisoryAddOnsParams, RecordSupervisoryAddOnRequestInput } from "@assayline/core/supervisory/types";

export type ListSupervisoryAddOnsInput = ListSupervisoryAddOnsParams;

export type RecordSupervisoryAddOnInput = RecordSupervisoryAddOnRequestInput;

export type ListSupervisoryAddOnsOutput = {};

export type RecordSupervisoryAddOnOutput = {};
