/**
 * UseException Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { UseExceptionEntity } from "@assayline/core/use/models/index.js";
import { useSchemas } from "@assayline/core/use";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "use";

export function createUseException(overrides: Partial<UseExceptionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    modelId: overrides.modelId ?? faker.string.uuid(),
    requestedUse: overrides.requestedUse ?? faker.lorem.word(),
    status: overrides.status ?? "requested",
    ...overrides,
  };

  return useSchemas.UseException.parse(raw);
}

export function useExceptionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createUseException(overrides));
}
