/**
 * TierCriteriumRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TierCriteriumRepository Port
 *
 * DDD: Application port for tiercriteriumrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetTierCriteriaInput, GetTierCriteriaOutput, UpdateTierCriteriaInput, UpdateTierCriteriaOutput } from "../dto/tier-criterium.dto";
export interface TierCriteriumRepository {
  getTierCriteria(input: GetTierCriteriaInput): Promise<GetTierCriteriaOutput>;
  updateTierCriteria(input: UpdateTierCriteriaInput): Promise<UpdateTierCriteriaOutput>;
}

export type { GetTierCriteriaInput, GetTierCriteriaOutput, UpdateTierCriteriaInput, UpdateTierCriteriaOutput } from "../dto/tier-criterium.dto";
