/**
 * ExecuteRecordMonitoringBreach - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordMonitoringBreach Use Case
 *
 * DDD: Application use case for get Breach.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordMonitoringBreachInput, RecordMonitoringBreachOutput } from "../dto/breach.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { BreachRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordMonitoringBreach {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly breach: BreachRepository
  ) {}

  async execute(input: RecordMonitoringBreachInput): Promise<RecordMonitoringBreachOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: breachedAt, obligationId, observedValue
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).obligationId) {
      throw new ValidationError("obligationId is required");
    }
    const obligationId = (input as any).obligationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.breach.recordMonitoringBreach({ obligationId: obligationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${obligationId}`);
    }

    return entity as RecordMonitoringBreachOutput;
  }
}
