/**
 * Handlers for Obligation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MonitoringDomainModule } from "../dependencies/monitoring-ddd.dependencies.js";
import type { AssignMonitoringObligationInput, ListMonitoringObligationsInput } from "@assayline/services/monitoring";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/monitoring/obligations
 * Operation: listMonitoringObligations
 */
export async function listMonitoringObligations(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], modelId?: string | string[], inBreach?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: MonitoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListMonitoringObligationsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.obligations.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/monitoring/obligations
 * Operation: assignMonitoringObligation
 */
export async function assignMonitoringObligation(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: MonitoringDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AssignMonitoringObligationInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.obligations.get.execute(input);
  return reply.code(201).send(result);
}


