/**
 * ExecuteListArtefacts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListArtefacts Use Case
 *
 * DDD: Application use case for list Artefact.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListArtefactsInput, ListArtefactsOutput } from "../dto/artefact.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { ArtefactRepository } from "../ports";

export class ExecuteListArtefacts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly artefact: ArtefactRepository
  ) {}

  async execute(input: ListArtefactsInput): Promise<ListArtefactsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.invId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.artefact.listArtefacts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListArtefactsOutput;
  }
}
