/**
 * GetCapacityForecast DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetCapacityForecastParams } from "@assayline/core/validation";

export function createGetCapacityForecastRequest(overrides: Partial<GetCapacityForecastParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
