/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Supervisory Domain Use Cases
 * 
 * List of all use case names for the supervisory domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SUPERVISORY_USE_CASES = [
  "executeAssembleSupervisoryPack",
  "executeGetSupervisoryPack",
  "executeListSupervisoryAddOns",
  "executeRecordSupervisoryAddOn",
  "executeUpdateRemediationPlan"
] as const;
