/**
 * RevalidationTrigger Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RevalidationTriggerEntity } from "@assayline/core/monitoring/models/index.js";
import { monitoringSchemas } from "@assayline/core/monitoring";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mon";

export function createRevalidationTrigger(overrides: Partial<RevalidationTriggerEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    modelId: overrides.modelId ?? faker.string.uuid(),
    reason: overrides.reason ?? "monitoring_breach",
    status: overrides.status ?? "open",
    ...overrides,
  };

  return monitoringSchemas.RevalidationTrigger.parse(raw);
}

export function revalidationTriggerBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRevalidationTrigger(overrides));
}
