/**
 * Routes for CompletenessCheck
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { checkSubmissionCompleteness } from "../handlers/completeness-check.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function completenessCheckRoutes(fastify: FastifyInstance) {
  // POST /v1/submissions/{submissionId}/completeness-check (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/submissions/:submissionId/completeness-check",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { submissionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSubmissionsDependenciesForRequest();
        await checkSubmissionCompleteness(request, reply, deps);
      });
    }
  );


}
