/**
 * ConservatismOverlayRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConservatismOverlayRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConservatismOverlayRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConservatismOverlayRepository,
} from "@assayline/services/conservatism";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConservatismOverlayRepositoryDdb } from "./conservatism-overlay-repository.ddb.js";

/**
 * ConservatismOverlayRepositoryAdapter
 *
 * Implements ConservatismOverlayRepository port for infrastructure layer.
 */
export class ConservatismOverlayRepositoryAdapter implements ConservatismOverlayRepository {
  private readonly ddb: ConservatismOverlayRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConservatismOverlayRepositoryDdb(this.dynamoClient);
  }

  async listConservatismOverlays(input: Parameters<ConservatismOverlayRepository['listConservatismOverlays']>[0]): Promise<Awaited<ReturnType<ConservatismOverlayRepository['listConservatismOverlays']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConservatismOverlays(input);
  }

  async declareConservatismOverlay(input: Parameters<ConservatismOverlayRepository['declareConservatismOverlay']>[0]): Promise<Awaited<ReturnType<ConservatismOverlayRepository['declareConservatismOverlay']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.declareConservatismOverlay(input);
  }
}
