/**
 * ExecuteListConservatismOverlays - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListConservatismOverlays Use Case
 *
 * DDD: Application use case for list ConservatismOverlay.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListConservatismOverlaysInput, ListConservatismOverlaysOutput } from "../dto/conservatism-overlay.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { ConservatismOverlayRepository } from "../ports";

export class ExecuteListConservatismOverlays {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly conservatismOverlay: ConservatismOverlayRepository
  ) {}

  async execute(input: ListConservatismOverlaysInput): Promise<ListConservatismOverlaysOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.conservatismOverlay.listConservatismOverlays({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListConservatismOverlaysOutput;
  }
}
