/**
 * ExecuteDeclareConservatismOverlay - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDeclareConservatismOverlay Use Case
 *
 * DDD: Application use case for get ConservatismOverlay.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DeclareConservatismOverlayInput, DeclareConservatismOverlayOutput } from "../dto/conservatism-overlay.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { ConservatismOverlayRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDeclareConservatismOverlay {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly conservatismOverlay: ConservatismOverlayRepository
  ) {}

  async execute(input: DeclareConservatismOverlayInput): Promise<DeclareConservatismOverlayOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnsId();

    // All field names extracted from OpenAPI spec: location, magnitude, modelId, rationale, reviewDate
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelId) {
      throw new ValidationError("modelId is required");
    }
    const modelId = (input as any).modelId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.conservatismOverlay.declareConservatismOverlay({ modelId: modelId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${modelId}`);
    }

    return entity as DeclareConservatismOverlayOutput;
  }
}
