/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Tiering Domain Use Cases
 * 
 * List of all use case names for the tiering domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const TIERING_USE_CASES = [
  "executeAssessModelTier",
  "executeGetTierCriteria",
  "executeListTierAssessments",
  "executeUpdateTierCriteria"
] as const;
