/**
 * Tiering DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Tiering Domain Module - Composition root
 *
 * DDD: Composition root for tiering domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  TierAssessmentRepositoryAdapter,
  TierCriteriumRepositoryAdapter,
} from "@assayline/adapters/tiering";
import { getIdGeneratorService } from "@assayline/adapters";
import type { AdapterDynamoDBClient } from "@assayline/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAssessModelTier,
  ExecuteGetTierCriteria,
  ExecuteListTierAssessments,
  ExecuteUpdateTierCriteria,
} from "@assayline/services/tiering/usecases";
// Ports (interfaces)
import type {
  TierAssessmentRepository,
  TierCriteriumRepository,
} from "@assayline/services/tiering/ports";

export interface TieringDomainModule {
  repos: {
    tierAssessments: TierAssessmentRepository;
    tierCriteria: TierCriteriumRepository;
  };
  useCases: {
    tierAssessments: {
      get: ExecuteAssessModelTier;
      list: ExecuteListTierAssessments;
    };
    tierCriteria: {
      get: ExecuteGetTierCriteria;
      update: ExecuteUpdateTierCriteria;
    };
  };
}

export function buildTieringDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TieringDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      tierAssessments?: TierAssessmentRepository;
      tierCriteria?: TierCriteriumRepository;
    } = {};

    obj.tierAssessments = new TierAssessmentRepositoryAdapter(dynamoClient);
    obj.tierCriteria = new TierCriteriumRepositoryAdapter(dynamoClient);
    return {
      tierAssessments: obj.tierAssessments!,
      tierCriteria: obj.tierCriteria!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    tierAssessments: {
      get: new ExecuteAssessModelTier(executionContext, idGenerator, repos.tierAssessments),
      list: new ExecuteListTierAssessments(executionContext, idGenerator, repos.tierAssessments),
    },
    tierCriteria: {
      get: new ExecuteGetTierCriteria(executionContext, idGenerator, repos.tierCriteria),
      update: new ExecuteUpdateTierCriteria(executionContext, idGenerator, repos.tierCriteria),
    },
  };
  return { repos, useCases: useCases as TieringDomainModule["useCases"] };
}
