/**
 * SupervisoryAddOn Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { SupervisoryAddOnEntity } from "@assayline/core/supervisory/models/index.js";
import { supervisorySchemas } from "@assayline/core/supervisory";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "spv";

export function createSupervisoryAddOn(overrides: Partial<SupervisoryAddOnEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    amount: overrides.amount ?? {
      amount: "",
      currency: ""
    },
    status: overrides.status ?? "open",
    ...overrides,
  };

  return supervisorySchemas.SupervisoryAddOn.parse(raw);
}

export function supervisoryAddOnBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSupervisoryAddOn(overrides));
}
