/**
 * Routes for Engagement
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createValidationEngagement, listValidationEngagements } from "../handlers/engagement.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function engagementRoutes(fastify: FastifyInstance) {
  // POST /v1/validation/engagements (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/validation/engagements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationDependenciesForRequest();
        await createValidationEngagement(request, reply, deps);
      });
    }
  );


  // GET /v1/validation/engagements (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/validation/engagements",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationDependenciesForRequest();
        await listValidationEngagements(request, reply, deps);
      });
    }
  );


}
