/**
 * Routes for Task
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listValidationTasks, placeValidationTask } from "../handlers/task.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function taskRoutes(fastify: FastifyInstance) {
  // GET /v1/validation/engagements/{engagementId}/tasks (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/validation/engagements/:engagementId/tasks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { engagementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationDependenciesForRequest();
        await listValidationTasks(request, reply, deps);
      });
    }
  );


  // POST /v1/validation/engagements/{engagementId}/tasks (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/validation/engagements/:engagementId/tasks",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { engagementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getValidationDependenciesForRequest();
        await placeValidationTask(request, reply, deps);
      });
    }
  );


}
