/**
 * ListTierAssessment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListTierAssessmentsParams } from "@assayline/core/tiering";

export function createListTierAssessmentRequest(overrides: Partial<ListTierAssessmentsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
