/**
 * CloseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CloseRepository Port
 *
 * DDD: Application port for closerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CloseFindingInput, CloseFindingOutput } from "../dto/close.dto";
export interface CloseRepository {
  closeFinding(input: CloseFindingInput): Promise<CloseFindingOutput>;
}

export type { CloseFindingInput, CloseFindingOutput } from "../dto/close.dto";
