/**
 * Repository interface for RevalidationTrigger
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RevalidationTriggerEntity
} from "../models/revalidation-trigger.entity.js";
import type {
  ListRevalidationTriggersParams
} from "../types/index.js";
/**
 * RevalidationTriggerRepository Interface
 */
export interface RevalidationTriggerRepository extends ReadRepository<RevalidationTriggerEntity, string, ListRevalidationTriggersParams> {

}
