/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@assayline/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@assayline/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@assayline/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _conservatism from "./conservatism/index.js";
import * as _findings from "./findings/index.js";
import * as _identity from "./identity/index.js";
import * as _inventory from "./inventory/index.js";
import * as _monitoring from "./monitoring/index.js";
import * as _quantification from "./quantification/index.js";
import * as _submissions from "./submissions/index.js";
import * as _supervisory from "./supervisory/index.js";
import * as _tiering from "./tiering/index.js";
import * as _use from "./use/index.js";
import * as _validation from "./validation/index.js";

// Export as namespaces
export const conservatism = _conservatism;
export const findings = _findings;
export const identity = _identity;
export const inventory = _inventory;
export const monitoring = _monitoring;
export const quantification = _quantification;
export const submissions = _submissions;
export const supervisory = _supervisory;
export const tiering = _tiering;
export const use = _use;
export const validation = _validation;
