/**
 * ExecuteAssessModelTier - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAssessModelTier Use Case
 *
 * DDD: Application use case for get TierAssessment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AssessModelTierInput, AssessModelTierOutput } from "../dto/tier-assessment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { TierAssessmentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAssessModelTier {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly tierAssessment: TierAssessmentRepository
  ) {}

  async execute(input: AssessModelTierInput): Promise<AssessModelTierOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tirId();

    // All field names extracted from OpenAPI spec: rationale, scores, tier
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelId) {
      throw new ValidationError("modelId is required");
    }
    const modelId = (input as any).modelId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.tierAssessment.assessModelTier({ modelId: modelId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${modelId}`);
    }

    return entity as AssessModelTierOutput;
  }
}
