/**
 * ExecuteListTierAssessments - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTierAssessments Use Case
 *
 * DDD: Application use case for list TierAssessment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTierAssessmentsInput, ListTierAssessmentsOutput } from "../dto/tier-assessment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { TierAssessmentRepository } from "../ports";

export class ExecuteListTierAssessments {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly tierAssessment: TierAssessmentRepository
  ) {}

  async execute(input: ListTierAssessmentsInput): Promise<ListTierAssessmentsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tirId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.tierAssessment.listTierAssessments({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTierAssessmentsOutput;
  }
}
