/**
 * Routes for ConservatismOverlay
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { declareConservatismOverlay, listConservatismOverlays } from "../handlers/conservatism-overlay.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function conservatismOverlayRoutes(fastify: FastifyInstance) {
  // POST /v1/conservatism-overlays (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/conservatism-overlays",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConservatismDependenciesForRequest();
        await declareConservatismOverlay(request, reply, deps);
      });
    }
  );


  // GET /v1/conservatism-overlays (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/conservatism-overlays",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConservatismDependenciesForRequest();
        await listConservatismOverlays(request, reply, deps);
      });
    }
  );


}
