/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { aggregateRoutes } from "./aggregate.routes.js";
export { conservatismOverlayRoutes } from "./conservatism-overlay.routes.js";
