/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/quantifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quantifications */
        get: operations["listQuantifications"];
        put?: never;
        /** Record Quantification */
        post: operations["recordQuantification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk-appetite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Risk Appetite Statement */
        get: operations["getRiskAppetiteStatement"];
        /** Update Risk Appetite Statement */
        put: operations["updateRiskAppetiteStatement"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lump-sum-buffers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lump Sum Buffers */
        get: operations["listLumpSumBuffers"];
        put?: never;
        /** Fix Lump Sum Buffer */
        post: operations["fixLumpSumBuffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description ISO 4217 currency code.
         * @example USD
         */
        Currency: string;
        /** @description Decimal-string amount + currency (never IEEE float). */
        Money: {
            /**
             * @description Signed decimal string with up to 5 fractional digits.
             * @example 1234.56
             */
            amount: string;
            /**
             * @description ISO 4217 currency code.
             * @example USD
             */
            currency: string;
        };
        ModelRiskQuantification: {
            id: string;
            modelId?: string;
            /** @enum {string} */
            scope: "per_model" | "aggregate";
            /** @description Decimal-string amount + currency (never IEEE float). */
            quantifiedAmount?: {
                /**
                 * @description Signed decimal string with up to 5 fractional digits.
                 * @example 1234.56
                 */
                amount: string;
                /**
                 * @description ISO 4217 currency code.
                 * @example USD
                 */
                currency: string;
            };
            /** @enum {string} */
            status: "quantified" | "unquantifiable";
            /** @enum {string} */
            againstAppetite?: "within" | "near" | "breached";
            kpiSnapshot?: {
                [key: string]: number;
            };
            /** Format: date-time */
            assessedAt?: string;
        };
        ModelRiskQuantificationListData: {
            items: {
                id: string;
                modelId?: string;
                /** @enum {string} */
                scope: "per_model" | "aggregate";
                /** @description Decimal-string amount + currency (never IEEE float). */
                quantifiedAmount?: {
                    /**
                     * @description Signed decimal string with up to 5 fractional digits.
                     * @example 1234.56
                     */
                    amount: string;
                    /**
                     * @description ISO 4217 currency code.
                     * @example USD
                     */
                    currency: string;
                };
                /** @enum {string} */
                status: "quantified" | "unquantifiable";
                /** @enum {string} */
                againstAppetite?: "within" | "near" | "breached";
                kpiSnapshot?: {
                    [key: string]: number;
                };
                /** Format: date-time */
                assessedAt?: string;
            }[];
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            timestamp?: string;
        };
        ModelRiskQuantificationListResponse: {
            data: {
                items: {
                    id: string;
                    modelId?: string;
                    /** @enum {string} */
                    scope: "per_model" | "aggregate";
                    /** @description Decimal-string amount + currency (never IEEE float). */
                    quantifiedAmount?: {
                        /**
                         * @description Signed decimal string with up to 5 fractional digits.
                         * @example 1234.56
                         */
                        amount: string;
                        /**
                         * @description ISO 4217 currency code.
                         * @example USD
                         */
                        currency: string;
                    };
                    /** @enum {string} */
                    status: "quantified" | "unquantifiable";
                    /** @enum {string} */
                    againstAppetite?: "within" | "near" | "breached";
                    kpiSnapshot?: {
                        [key: string]: number;
                    };
                    /** Format: date-time */
                    assessedAt?: string;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                timestamp?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        ModelRiskQuantificationCreate: {
            modelId?: string;
            /** @enum {string} */
            scope: "per_model" | "aggregate";
            /** @description Decimal-string amount + currency (never IEEE float). */
            quantifiedAmount?: {
                /**
                 * @description Signed decimal string with up to 5 fractional digits.
                 * @example 1234.56
                 */
                amount: string;
                /**
                 * @description ISO 4217 currency code.
                 * @example USD
                 */
                currency: string;
            };
            /** @enum {string} */
            status: "quantified" | "unquantifiable";
            kpiSnapshot?: {
                [key: string]: number;
            };
        };
        ModelRiskQuantificationResponse: {
            data: {
                id: string;
                modelId?: string;
                /** @enum {string} */
                scope: "per_model" | "aggregate";
                /** @description Decimal-string amount + currency (never IEEE float). */
                quantifiedAmount?: {
                    /**
                     * @description Signed decimal string with up to 5 fractional digits.
                     * @example 1234.56
                     */
                    amount: string;
                    /**
                     * @description ISO 4217 currency code.
                     * @example USD
                     */
                    currency: string;
                };
                /** @enum {string} */
                status: "quantified" | "unquantifiable";
                /** @enum {string} */
                againstAppetite?: "within" | "near" | "breached";
                kpiSnapshot?: {
                    [key: string]: number;
                };
                /** Format: date-time */
                assessedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                timestamp?: string;
            };
        };
        RiskAppetiteStatement: {
            version: string;
            narrative?: string;
            kpis: {
                /** @description At minimum model performance and open validation findings */
                name: string;
                /** Format: float */
                threshold: number;
                unit?: string;
            }[];
            approvedBy?: string;
            /** Format: date-time */
            approvedAt?: string;
        };
        RiskAppetiteStatementResponse: {
            data: {
                version: string;
                narrative?: string;
                kpis: {
                    /** @description At minimum model performance and open validation findings */
                    name: string;
                    /** Format: float */
                    threshold: number;
                    unit?: string;
                }[];
                approvedBy?: string;
                /** Format: date-time */
                approvedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                timestamp?: string;
            };
        };
        LumpSumBuffer: {
            id: string;
            modelId?: string;
            /** @description Decimal-string amount + currency (never IEEE float). */
            amount: {
                /**
                 * @description Signed decimal string with up to 5 fractional digits.
                 * @example 1234.56
                 */
                amount: string;
                /**
                 * @description ISO 4217 currency code.
                 * @example USD
                 */
                currency: string;
            };
            rationale: string;
            /** Format: date-time */
            fixedAt?: string;
        };
        LumpSumBufferListData: {
            items: {
                id: string;
                modelId?: string;
                /** @description Decimal-string amount + currency (never IEEE float). */
                amount: {
                    /**
                     * @description Signed decimal string with up to 5 fractional digits.
                     * @example 1234.56
                     */
                    amount: string;
                    /**
                     * @description ISO 4217 currency code.
                     * @example USD
                     */
                    currency: string;
                };
                rationale: string;
                /** Format: date-time */
                fixedAt?: string;
            }[];
        };
        LumpSumBufferListResponse: {
            data: {
                items: {
                    id: string;
                    modelId?: string;
                    /** @description Decimal-string amount + currency (never IEEE float). */
                    amount: {
                        /**
                         * @description Signed decimal string with up to 5 fractional digits.
                         * @example 1234.56
                         */
                        amount: string;
                        /**
                         * @description ISO 4217 currency code.
                         * @example USD
                         */
                        currency: string;
                    };
                    rationale: string;
                    /** Format: date-time */
                    fixedAt?: string;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                timestamp?: string;
            };
        };
        LumpSumBufferCreate: {
            modelId?: string;
            /** @description Decimal-string amount + currency (never IEEE float). */
            amount: {
                /**
                 * @description Signed decimal string with up to 5 fractional digits.
                 * @example 1234.56
                 */
                amount: string;
                /**
                 * @description ISO 4217 currency code.
                 * @example USD
                 */
                currency: string;
            };
            rationale: string;
        };
        LumpSumBufferResponse: {
            data: {
                id: string;
                modelId?: string;
                /** @description Decimal-string amount + currency (never IEEE float). */
                amount: {
                    /**
                     * @description Signed decimal string with up to 5 fractional digits.
                     * @example 1234.56
                     */
                    amount: string;
                    /**
                     * @description ISO 4217 currency code.
                     * @example USD
                     */
                    currency: string;
                };
                rationale: string;
                /** Format: date-time */
                fixedAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                timestamp?: string;
            };
        };
    };
    responses: {
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listQuantifications: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                modelId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model risk quantifications page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                modelId?: string;
                                /** @enum {string} */
                                scope: "per_model" | "aggregate";
                                /** @description Decimal-string amount + currency (never IEEE float). */
                                quantifiedAmount?: {
                                    /**
                                     * @description Signed decimal string with up to 5 fractional digits.
                                     * @example 1234.56
                                     */
                                    amount: string;
                                    /**
                                     * @description ISO 4217 currency code.
                                     * @example USD
                                     */
                                    currency: string;
                                };
                                /** @enum {string} */
                                status: "quantified" | "unquantifiable";
                                /** @enum {string} */
                                againstAppetite?: "within" | "near" | "breached";
                                kpiSnapshot?: {
                                    [key: string]: number;
                                };
                                /** Format: date-time */
                                assessedAt?: string;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recordQuantification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    modelId?: string;
                    /** @enum {string} */
                    scope: "per_model" | "aggregate";
                    /** @description Decimal-string amount + currency (never IEEE float). */
                    quantifiedAmount?: {
                        /**
                         * @description Signed decimal string with up to 5 fractional digits.
                         * @example 1234.56
                         */
                        amount: string;
                        /**
                         * @description ISO 4217 currency code.
                         * @example USD
                         */
                        currency: string;
                    };
                    /** @enum {string} */
                    status: "quantified" | "unquantifiable";
                    kpiSnapshot?: {
                        [key: string]: number;
                    };
                };
            };
        };
        responses: {
            /** @description Quantification recorded against appetite */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            modelId?: string;
                            /** @enum {string} */
                            scope: "per_model" | "aggregate";
                            /** @description Decimal-string amount + currency (never IEEE float). */
                            quantifiedAmount?: {
                                /**
                                 * @description Signed decimal string with up to 5 fractional digits.
                                 * @example 1234.56
                                 */
                                amount: string;
                                /**
                                 * @description ISO 4217 currency code.
                                 * @example USD
                                 */
                                currency: string;
                            };
                            /** @enum {string} */
                            status: "quantified" | "unquantifiable";
                            /** @enum {string} */
                            againstAppetite?: "within" | "near" | "breached";
                            kpiSnapshot?: {
                                [key: string]: number;
                            };
                            /** Format: date-time */
                            assessedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getRiskAppetiteStatement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stated model risk appetite and KPIs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            version: string;
                            narrative?: string;
                            kpis: {
                                /** @description At minimum model performance and open validation findings */
                                name: string;
                                /** Format: float */
                                threshold: number;
                                unit?: string;
                            }[];
                            approvedBy?: string;
                            /** Format: date-time */
                            approvedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateRiskAppetiteStatement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: string;
                    narrative?: string;
                    kpis: {
                        /** @description At minimum model performance and open validation findings */
                        name: string;
                        /** Format: float */
                        threshold: number;
                        unit?: string;
                    }[];
                    approvedBy?: string;
                    /** Format: date-time */
                    approvedAt?: string;
                };
            };
        };
        responses: {
            /** @description Appetite updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            version: string;
                            narrative?: string;
                            kpis: {
                                /** @description At minimum model performance and open validation findings */
                                name: string;
                                /** Format: float */
                                threshold: number;
                                unit?: string;
                            }[];
                            approvedBy?: string;
                            /** Format: date-time */
                            approvedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listLumpSumBuffers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documented buffers where quantification is impossible */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                modelId?: string;
                                /** @description Decimal-string amount + currency (never IEEE float). */
                                amount: {
                                    /**
                                     * @description Signed decimal string with up to 5 fractional digits.
                                     * @example 1234.56
                                     */
                                    amount: string;
                                    /**
                                     * @description ISO 4217 currency code.
                                     * @example USD
                                     */
                                    currency: string;
                                };
                                rationale: string;
                                /** Format: date-time */
                                fixedAt?: string;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    fixLumpSumBuffer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    modelId?: string;
                    /** @description Decimal-string amount + currency (never IEEE float). */
                    amount: {
                        /**
                         * @description Signed decimal string with up to 5 fractional digits.
                         * @example 1234.56
                         */
                        amount: string;
                        /**
                         * @description ISO 4217 currency code.
                         * @example USD
                         */
                        currency: string;
                    };
                    rationale: string;
                };
            };
        };
        responses: {
            /** @description Buffer fixed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            modelId?: string;
                            /** @description Decimal-string amount + currency (never IEEE float). */
                            amount: {
                                /**
                                 * @description Signed decimal string with up to 5 fractional digits.
                                 * @example 1234.56
                                 */
                                amount: string;
                                /**
                                 * @description ISO 4217 currency code.
                                 * @example USD
                                 */
                                currency: string;
                            };
                            rationale: string;
                            /** Format: date-time */
                            fixedAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            timestamp?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
