/**
 * Obligation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Obligation DTOs
 *
 * DDD: Application DTOs for Obligation use cases.
 */

import type { AssignMonitoringObligationRequestInput, ListMonitoringObligationsParams } from "@assayline/core/monitoring/types";

export type ListMonitoringObligationsInput = ListMonitoringObligationsParams;

export type AssignMonitoringObligationInput = AssignMonitoringObligationRequestInput;

export type ListMonitoringObligationsOutput = {};

export type AssignMonitoringObligationOutput = {};
