/**
 * RevalidationTrigger DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevalidationTrigger DTOs
 *
 * DDD: Application DTOs for RevalidationTrigger use cases.
 */

import type { ListRevalidationTriggersParams } from "@assayline/core/monitoring/types";

export type ListRevalidationTriggersInput = ListRevalidationTriggersParams;

export type ListRevalidationTriggersOutput = {};
