/**
 * ExecuteAuthoriseUseException - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAuthoriseUseException Use Case
 *
 * DDD: Application use case for get Authorise.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AuthoriseUseExceptionInput, AuthoriseUseExceptionOutput } from "../dto/authorise.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { AuthoriseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAuthoriseUseException {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly authorise: AuthoriseRepository
  ) {}

  async execute(input: AuthoriseUseExceptionInput): Promise<AuthoriseUseExceptionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.useId();

    // All field names extracted from OpenAPI spec: committeeReference, compensatingConditions, decision, expiry
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).exceptionId) {
      throw new ValidationError("exceptionId is required");
    }
    const exceptionId = (input as any).exceptionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.authorise.authoriseUseException({ exceptionId: exceptionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${exceptionId}`);
    }

    return entity as AuthoriseUseExceptionOutput;
  }
}
