/**
 * ExecuteSetPermittedUse - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSetPermittedUse Use Case
 *
 * DDD: Application use case for update PermittedUse.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SetPermittedUseInput, SetPermittedUseOutput } from "../dto/permitted-use.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { PermittedUseRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteSetPermittedUse {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly permittedUse: PermittedUseRepository
  ) {}

  async execute(input: SetPermittedUseInput): Promise<SetPermittedUseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.useId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelId) {
      throw new ValidationError("modelId is required");
    }
    const modelId = (input as any).modelId;

    // Load existing entity
    const existing = await this.permittedUse.getPermittedUse({ modelId: modelId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${modelId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.permittedUse.setPermittedUse({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as SetPermittedUseOutput;
  }
}
