/**
 * ExecuteCreateValidationEngagement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateValidationEngagement Use Case
 *
 * DDD: Application use case for create Engagement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateValidationEngagementInput, CreateValidationEngagementOutput } from "../dto/engagement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { EngagementRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateValidationEngagement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly engagement: EngagementRepository
  ) {}

  async execute(input: CreateValidationEngagementInput): Promise<CreateValidationEngagementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.valId();

    // All field names extracted from OpenAPI spec: leadValidatorId, modelId, slotId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.modelId) {
      throw new ValidationError("modelId is required");
    }
    if (!input.leadValidatorId) {
      throw new ValidationError("leadValidatorId is required");
    }
    if (!input.slotId) {
      throw new ValidationError("slotId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (validation domain)
    const entityId = this.idGenerator.valId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.engagement.createValidationEngagement({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateValidationEngagementOutput;
  }
}
