/**
 * ExecuteListValidationSlots - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListValidationSlots Use Case
 *
 * DDD: Application use case for list Slot.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListValidationSlotsInput, ListValidationSlotsOutput } from "../dto/slot.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { SlotRepository } from "../ports";

export class ExecuteListValidationSlots {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly slot: SlotRepository
  ) {}

  async execute(input: ListValidationSlotsInput): Promise<ListValidationSlotsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.valId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.slot.listValidationSlots({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListValidationSlotsOutput;
  }
}
