/**
 * ExecutePlaceValidationTask - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecutePlaceValidationTask Use Case
 *
 * DDD: Application use case for get Task.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { PlaceValidationTaskInput, PlaceValidationTaskOutput } from "../dto/task.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { TaskRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecutePlaceValidationTask {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly task: TaskRepository
  ) {}

  async execute(input: PlaceValidationTaskInput): Promise<PlaceValidationTaskOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.valId();

    // All field names extracted from OpenAPI spec: assigneeId, dataSensitivityBasis, placement, taskType
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).engagementId) {
      throw new ValidationError("engagementId is required");
    }
    const engagementId = (input as any).engagementId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.task.placeValidationTask({ engagementId: engagementId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${engagementId}`);
    }

    return entity as PlaceValidationTaskOutput;
  }
}
