/**
 * ExecuteGetCapacityForecast - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetCapacityForecast Use Case
 *
 * DDD: Application use case for get CapacityForecast.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCapacityForecastInput, GetCapacityForecastOutput } from "../dto/capacity-forecast.dto";
import type { ExecutionContextService, IdGeneratorService } from "@assayline/services/_shared/index.js";
import type { CapacityForecastRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetCapacityForecast {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly capacityForecast: CapacityForecastRepository
  ) {}

  async execute(input: GetCapacityForecastInput): Promise<GetCapacityForecastOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.valId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.capacityForecast.getCapacityForecast({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetCapacityForecastOutput;
  }
}
