/**
 * SupervisoryPack Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/supervisory.openapi.types.js";
import { schemas } from "../schemas/supervisory.schemas.js";

/**
 * Entity: SupervisoryPackEntity
 * Description: Represents the SupervisoryPack domain model.
 * Source: schemas.SupervisoryPack
 * Type: Domain Entity (API)
 */
export const SupervisoryPackEntitySchema = schemas.SupervisoryPack;
export type SupervisoryPackEntity = components["schemas"]["SupervisoryPack"];
