/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { supervisoryAddOnRoutes } from "./supervisory-add-on.routes.js";
export { remediationRoutes } from "./remediation.routes.js";
export { supervisoryPackRoutes } from "./supervisory-pack.routes.js";
