/**
 * Routes for Remediation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { updateRemediationPlan } from "../handlers/remediation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function remediationRoutes(fastify: FastifyInstance) {
  // PUT /v1/supervisory-add-ons/{addOnId}/remediation (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/supervisory-add-ons/:addOnId/remediation",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { addOnId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSupervisoryDependenciesForRequest();
        await updateRemediationPlan(request, reply, deps);
      });
    }
  );


}
