/**
 * CompletenessCheckRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompletenessCheckRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CompletenessCheckRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CompletenessCheckRepository,
} from "@assayline/services/submissions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CompletenessCheckRepositoryDdb } from "./completeness-check-repository.ddb.js";

/**
 * CompletenessCheckRepositoryAdapter
 *
 * Implements CompletenessCheckRepository port for infrastructure layer.
 */
export class CompletenessCheckRepositoryAdapter implements CompletenessCheckRepository {
  private readonly ddb: CompletenessCheckRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CompletenessCheckRepositoryDdb(this.dynamoClient);
  }

  async checkSubmissionCompleteness(input: Parameters<CompletenessCheckRepository['checkSubmissionCompleteness']>[0]): Promise<Awaited<ReturnType<CompletenessCheckRepository['checkSubmissionCompleteness']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.checkSubmissionCompleteness(input);
  }
}
