/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Validation Domain Use Cases
 * 
 * List of all use case names for the validation domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const VALIDATION_USE_CASES = [
  "executeAllocateValidationSlot",
  "executeCreateValidationEngagement",
  "executeGetCapacityForecast",
  "executeListValidationEngagements",
  "executeListValidationSlots",
  "executeListValidationTasks",
  "executePlaceValidationTask"
] as const;
