/**
 * TierCriterium Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { TierCriteriumEntity } from "@assayline/core/tiering/models/index.js";
import { tieringSchemas } from "@assayline/core/tiering";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "tir";

export function createTierCriterium(overrides: Partial<TierCriteriumEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    dimensions: overrides.dimensions ?? [],
    version: overrides.version ?? faker.lorem.word(),
    ...overrides,
  };

  return tieringSchemas.TierCriteria.parse(raw);
}

export function tierCriteriumBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createTierCriterium(overrides));
}
