/**
 * Handlers for Remediation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SupervisoryDomainModule } from "../dependencies/supervisory-ddd.dependencies.js";
import type { UpdateRemediationPlanInput } from "@assayline/services/supervisory";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for PUT /v1/supervisory-add-ons/{addOnId}/remediation
 * Operation: updateRemediationPlan
 */
export async function updateRemediationPlan(
  request: FastifyRequest<{ Params: { addOnId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SupervisoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateRemediationPlanInput = {
    addOnId: request.params.addOnId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.remediations.update.execute(input);
  return reply.code(200).send(result);
}


