/**
 * Handlers for SupervisoryAddOn
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SupervisoryDomainModule } from "../dependencies/supervisory-ddd.dependencies.js";
import type { ListSupervisoryAddOnsInput, RecordSupervisoryAddOnInput } from "@assayline/services/supervisory";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/supervisory-add-ons
 * Operation: listSupervisoryAddOns
 */
export async function listSupervisoryAddOns(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SupervisoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSupervisoryAddOnsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.addOns.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/supervisory-add-ons
 * Operation: recordSupervisoryAddOn
 */
export async function recordSupervisoryAddOn(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SupervisoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordSupervisoryAddOnInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.addOns.get.execute(input);
  return reply.code(201).send(result);
}


