/**
 * CompletenessCheckRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CompletenessCheckRepository Port
 *
 * DDD: Application port for completenesscheckrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CheckSubmissionCompletenessInput, CheckSubmissionCompletenessOutput } from "../dto/completeness-check.dto";
export interface CompletenessCheckRepository {
  checkSubmissionCompleteness(input: CheckSubmissionCompletenessInput): Promise<CheckSubmissionCompletenessOutput>;
}

export type { CheckSubmissionCompletenessInput, CheckSubmissionCompletenessOutput } from "../dto/completeness-check.dto";
