/**
 * ReturnRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReturnRepository Port
 *
 * DDD: Application port for returnrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ReturnSubmissionInput, ReturnSubmissionOutput } from "../dto/return.dto";
export interface ReturnRepository {
  returnSubmission(input: ReturnSubmissionInput): Promise<ReturnSubmissionOutput>;
}

export type { ReturnSubmissionInput, ReturnSubmissionOutput } from "../dto/return.dto";
