/**
 * SubmissionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmissionRepository Port
 *
 * DDD: Application port for submissionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateSubmissionInput, CreateSubmissionOutput, ListSubmissionsInput, ListSubmissionsOutput } from "../dto/submission.dto";
export interface SubmissionRepository {
  listSubmissions(input: ListSubmissionsInput): Promise<ListSubmissionsOutput>;
  createSubmission(input: CreateSubmissionInput): Promise<CreateSubmissionOutput>;
}

export type { CreateSubmissionInput, CreateSubmissionOutput, ListSubmissionsInput, ListSubmissionsOutput } from "../dto/submission.dto";
