/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./lump-sum-buffer-repository.ddb.js";
export * from "./quantification-repository.ddb.js";
export * from "./risk-appetite-repository.ddb.js";
export * from "./lump-sum-buffer-repository.adapter.js";
export * from "./quantification-repository.adapter.js";
export * from "./risk-appetite-repository.adapter.js";
