/**
 * RiskAppetiteRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskAppetiteRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RiskAppetiteRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RiskAppetiteRepository,
} from "@assayline/services/quantification";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RiskAppetiteRepositoryDdb } from "./risk-appetite-repository.ddb.js";

/**
 * RiskAppetiteRepositoryAdapter
 *
 * Implements RiskAppetiteRepository port for infrastructure layer.
 */
export class RiskAppetiteRepositoryAdapter implements RiskAppetiteRepository {
  private readonly ddb: RiskAppetiteRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RiskAppetiteRepositoryDdb(this.dynamoClient);
  }

  async getRiskAppetiteStatement(input: Parameters<RiskAppetiteRepository['getRiskAppetiteStatement']>[0]): Promise<Awaited<ReturnType<RiskAppetiteRepository['getRiskAppetiteStatement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRiskAppetiteStatement(input);
  }

  async updateRiskAppetiteStatement(input: Parameters<RiskAppetiteRepository['updateRiskAppetiteStatement']>[0]): Promise<Awaited<ReturnType<RiskAppetiteRepository['updateRiskAppetiteStatement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateRiskAppetiteStatement(input);
  }
}
