/**
 * ListSupervisoryAddOn DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListSupervisoryAddOnsParams } from "@assayline/core/supervisory";

export function createListSupervisoryAddOnRequest(overrides: Partial<ListSupervisoryAddOnsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
