/**
 * RevalidationTrigger Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitoring
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/monitoring.openapi.types.js";
import { schemas } from "../schemas/monitoring.schemas.js";

/**
 * Entity: RevalidationTriggerEntity
 * Description: Represents the RevalidationTrigger domain model.
 * Source: schemas.RevalidationTrigger
 * Type: Domain Entity (API)
 */
export const RevalidationTriggerEntitySchema = schemas.RevalidationTrigger;
export type RevalidationTriggerEntity = components["schemas"]["RevalidationTrigger"];
