/**
 * UseExceptionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UseExceptionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements UseExceptionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  UseExceptionRepository,
} from "@assayline/services/use";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { UseExceptionRepositoryDdb } from "./use-exception-repository.ddb.js";

/**
 * UseExceptionRepositoryAdapter
 *
 * Implements UseExceptionRepository port for infrastructure layer.
 */
export class UseExceptionRepositoryAdapter implements UseExceptionRepository {
  private readonly ddb: UseExceptionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new UseExceptionRepositoryDdb(this.dynamoClient);
  }

  async listUseExceptions(input: Parameters<UseExceptionRepository['listUseExceptions']>[0]): Promise<Awaited<ReturnType<UseExceptionRepository['listUseExceptions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listUseExceptions(input);
  }

  async requestUseException(input: Parameters<UseExceptionRepository['requestUseException']>[0]): Promise<Awaited<ReturnType<UseExceptionRepository['requestUseException']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.requestUseException(input);
  }
}
