/**
 * ArtefactRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ArtefactRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ArtefactRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ArtefactRepository,
} from "@assayline/services/inventory";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ArtefactRepositoryDdb } from "./artefact-repository.ddb.js";

/**
 * ArtefactRepositoryAdapter
 *
 * Implements ArtefactRepository port for infrastructure layer.
 */
export class ArtefactRepositoryAdapter implements ArtefactRepository {
  private readonly ddb: ArtefactRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ArtefactRepositoryDdb(this.dynamoClient);
  }

  async listArtefacts(input: Parameters<ArtefactRepository['listArtefacts']>[0]): Promise<Awaited<ReturnType<ArtefactRepository['listArtefacts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listArtefacts(input);
  }

  async registerArtefact(input: Parameters<ArtefactRepository['registerArtefact']>[0]): Promise<Awaited<ReturnType<ArtefactRepository['registerArtefact']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerArtefact(input);
  }
}
