/**
 * CapacityForecast Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/validation.openapi.types.js";
import { schemas } from "../schemas/validation.schemas.js";

/**
 * Entity: CapacityForecastEntity
 * Description: Represents the CapacityForecast domain model.
 * Source: schemas.CapacityForecast
 * Type: Domain Entity (API)
 */
export const CapacityForecastEntitySchema = schemas.CapacityForecast;
export type CapacityForecastEntity = components["schemas"]["CapacityForecast"];
