/**
 * Artefact Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/inventory.openapi.types.js";
import { schemas } from "../schemas/inventory.schemas.js";

/**
 * Entity: ArtefactEntity
 * Description: Represents the Artefact domain model.
 * Source: schemas.Artefact
 * Type: Domain Entity (API)
 */
export const ArtefactEntitySchema = schemas.Artefact;
export type ArtefactEntity = components["schemas"]["Artefact"];
