/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./capacity-forecast-repository.ddb.js";
export * from "./engagement-repository.ddb.js";
export * from "./slot-repository.ddb.js";
export * from "./task-repository.ddb.js";
export * from "./capacity-forecast-repository.adapter.js";
export * from "./engagement-repository.adapter.js";
export * from "./slot-repository.adapter.js";
export * from "./task-repository.adapter.js";
