/**
 * SlotRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: validation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlotRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SlotRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SlotRepository,
} from "@assayline/services/validation";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SlotRepositoryDdb } from "./slot-repository.ddb.js";

/**
 * SlotRepositoryAdapter
 *
 * Implements SlotRepository port for infrastructure layer.
 */
export class SlotRepositoryAdapter implements SlotRepository {
  private readonly ddb: SlotRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SlotRepositoryDdb(this.dynamoClient);
  }

  async listValidationSlots(input: Parameters<SlotRepository['listValidationSlots']>[0]): Promise<Awaited<ReturnType<SlotRepository['listValidationSlots']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listValidationSlots(input);
  }

  async allocateValidationSlot(input: Parameters<SlotRepository['allocateValidationSlot']>[0]): Promise<Awaited<ReturnType<SlotRepository['allocateValidationSlot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.allocateValidationSlot(input);
  }
}
