/**
 * LumpSumBuffer Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: quantification
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/quantification.openapi.types.js";
import { schemas } from "../schemas/quantification.schemas.js";

/**
 * Entity: LumpSumBufferEntity
 * Description: Represents the LumpSumBuffer domain model.
 * Source: schemas.LumpSumBuffer
 * Type: Domain Entity (API)
 */
export const LumpSumBufferEntitySchema = schemas.LumpSumBuffer;
export type LumpSumBufferEntity = components["schemas"]["LumpSumBuffer"];
