/**
 * Handlers for Submission
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SubmissionsDomainModule } from "../dependencies/submissions-ddd.dependencies.js";
import type { CreateSubmissionInput, ListSubmissionsInput } from "@assayline/services/submissions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/submissions
 * Operation: listSubmissions
 */
export async function listSubmissions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], submittingFunction?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSubmissionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.submissions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/submissions
 * Operation: createSubmission
 */
export async function createSubmission(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SubmissionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateSubmissionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.submissions.create.execute(input);
  return reply.code(201).send(result);
}


