/**
 * ListConservatismOverlay DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conservatism
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListConservatismOverlaysParams } from "@assayline/core/conservatism";

export function createListConservatismOverlayRequest(overrides: Partial<ListConservatismOverlaysParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
