/**
 * Use Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const setPermittedUse_Body = z
  .object({
    modelId: z.string(),
    allowedDecisions: z.array(z.string()),
    prohibitedDecisions: z.array(z.string()).optional(),
    constraints: z.array(z.string()).optional(),
    effectiveFrom: z.string().datetime({ offset: true }).optional(),
  })
  .passthrough();
const requestUseException_Body = z
  .object({
    modelId: z.string(),
    requestedUse: z.string(),
    businessJustification: z.string(),
    proposedExpiry: z.string().datetime({ offset: true }).optional(),
  })
  .passthrough();
const authoriseUseException_Body = z
  .object({
    decision: z.enum(['authorised', 'refused']),
    expiry: z.string().datetime({ offset: true }),
    compensatingConditions: z.array(z.string()),
    committeeReference: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  setPermittedUse_Body,
  requestUseException_Body,
  authoriseUseException_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/models/:modelId/permitted-use',
    alias: 'getPermittedUse',
    requestFormat: 'json',
    parameters: [
      {
        name: 'modelId',
        type: 'Path',
        schema: z.string(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            modelId: z.string(),
            allowedDecisions: z.array(z.string()),
            prohibitedDecisions: z.array(z.string()).optional(),
            constraints: z.array(z.string()).optional(),
            effectiveFrom: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
            timestamp: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'put',
    path: '/v1/models/:modelId/permitted-use',
    alias: 'setPermittedUse',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: setPermittedUse_Body,
      },
      {
        name: 'modelId',
        type: 'Path',
        schema: z.string(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            modelId: z.string(),
            allowedDecisions: z.array(z.string()),
            prohibitedDecisions: z.array(z.string()).optional(),
            constraints: z.array(z.string()).optional(),
            effectiveFrom: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
            timestamp: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/use-exceptions',
    alias: 'listUseExceptions',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['requested', 'authorised', 'expired', 'breached'])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string(),
                  modelId: z.string(),
                  requestedUse: z.string(),
                  status: z.enum([
                    'requested',
                    'authorised',
                    'expired',
                    'breached',
                    'refused',
                  ]),
                  expiry: z.string().datetime({ offset: true }).optional(),
                  compensatingConditions: z.array(z.string()).optional(),
                  committeeReference: z.string().optional(),
                })
                .passthrough()
            ),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
            timestamp: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/use-exceptions',
    alias: 'requestUseException',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: requestUseException_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string(),
            modelId: z.string(),
            requestedUse: z.string(),
            status: z.enum([
              'requested',
              'authorised',
              'expired',
              'breached',
              'refused',
            ]),
            expiry: z.string().datetime({ offset: true }).optional(),
            compensatingConditions: z.array(z.string()).optional(),
            committeeReference: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
            timestamp: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/use-exceptions/:exceptionId/authorise',
    alias: 'authoriseUseException',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: authoriseUseException_Body,
      },
      {
        name: 'exceptionId',
        type: 'Path',
        schema: z.string(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string(),
            modelId: z.string(),
            requestedUse: z.string(),
            status: z.enum([
              'requested',
              'authorised',
              'expired',
              'breached',
              'refused',
            ]),
            expiry: z.string().datetime({ offset: true }).optional(),
            compensatingConditions: z.array(z.string()).optional(),
            committeeReference: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
            timestamp: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
