/**
 * UseException Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/use.openapi.types.js";
import { schemas } from "../schemas/use.schemas.js";

/**
 * Entity: UseExceptionEntity
 * Description: Represents the UseException domain model.
 * Source: schemas.UseException
 * Type: Domain Entity (API)
 */
export const UseExceptionEntitySchema = schemas.UseException;
export type UseExceptionEntity = components["schemas"]["UseException"];
