/**
 * Repository interface for SupervisoryAddOn
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: supervisory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SupervisoryAddOnEntity
} from "../models/supervisory-add-on.entity.js";
import type {
  ListSupervisoryAddOnsParams,
  SupervisoryAddOn
} from "../types/index.js";
/**
 * SupervisoryAddOnRepository Interface
 */
export interface SupervisoryAddOnRepository extends CreateReadRepository<SupervisoryAddOnEntity, SupervisoryAddOn, string, ListSupervisoryAddOnsParams> {

}
