/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: submissions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the submissions domain.
 * Use these factories in tests to create test data.
 */

export { createCreateCompletenessCheckRequest } from "./completeness-check/dto/create-completeness-check.dto.factory.js";
export { createSubmission } from "./submission/entity/submission.entity.factory.js";
