/**
 * TierCriteriumRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: tiering
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TierCriteriumRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TierCriteriumRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TierCriteriumRepository,
} from "@assayline/services/tiering";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TierCriteriumRepositoryDdb } from "./tier-criterium-repository.ddb.js";

/**
 * TierCriteriumRepositoryAdapter
 *
 * Implements TierCriteriumRepository port for infrastructure layer.
 */
export class TierCriteriumRepositoryAdapter implements TierCriteriumRepository {
  private readonly ddb: TierCriteriumRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TierCriteriumRepositoryDdb(this.dynamoClient);
  }

  async getTierCriteria(input: Parameters<TierCriteriumRepository['getTierCriteria']>[0]): Promise<Awaited<ReturnType<TierCriteriumRepository['getTierCriteria']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTierCriteria(input);
  }

  async updateTierCriteria(input: Parameters<TierCriteriumRepository['updateTierCriteria']>[0]): Promise<Awaited<ReturnType<TierCriteriumRepository['updateTierCriteria']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateTierCriteria(input);
  }
}
