/**
 * CloseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CloseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CloseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CloseRepository,
} from "@assayline/services/findings";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CloseRepositoryDdb } from "./close-repository.ddb.js";

/**
 * CloseRepositoryAdapter
 *
 * Implements CloseRepository port for infrastructure layer.
 */
export class CloseRepositoryAdapter implements CloseRepository {
  private readonly ddb: CloseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CloseRepositoryDdb(this.dynamoClient);
  }

  async closeFinding(input: Parameters<CloseRepository['closeFinding']>[0]): Promise<Awaited<ReturnType<CloseRepository['closeFinding']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.closeFinding(input);
  }
}
