/**
 * DeterminationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeterminationRepository Port
 *
 * DDD: Application port for determinationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DetermineArtefactInput, DetermineArtefactOutput } from "../dto/determination.dto";
export interface DeterminationRepository {
  determineArtefact(input: DetermineArtefactInput): Promise<DetermineArtefactOutput>;
}

export type { DetermineArtefactInput, DetermineArtefactOutput } from "../dto/determination.dto";
